- This file has analysis with the range equivalent to Twitter
- Last date is 2020-12-04
- Start date is 2020-09-28

# Dotwin

## posts

In [11]:
import pandas as pd
import pyarrow
import matplotlib.pyplot as plt
import numpy as np

In [20]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-09-28')&(df1['timestamp'] <= '2020-12-05')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [21]:
df1=df1[["title"]]
df1

                                                  title
1225  14.5 or 10.5 5.56? What benis length is best? ...
1226  Meth took out the Christmas village way too ea...
1227                                 I’m okay with this
1228  Trump Protestestors Get Emotional When Asked S...
1229            Project Veritas - Absentee Ballot fraud
...                                                 ...
2205                                     Merry Wokemas!
2206  Never-Trump Traitor of Humanity Kelly Loeffler...
2207  I hope she gives a speech on women empowerment...
2208  #CNNRAW 9-8-20 from Project Veritas. 54 minute...
2209  Haroon Siddique (Guardian) engages in astonish...

[985 rows x 1 columns]

## comments

In [ ]:
file_path="../largedata/dotwin/dotwin_comments.pkl"
df2=pd.read_pickle(file_path)
df2["timestamp"]=pd.to_datetime(df2["timestamp"])
df2= df2[(df2['timestamp'] >= '2020-09-28')&(df2['timestamp'] <= '2020-12-05')]
df2