- This file has analysis with the range equivalent to Twitter
- Last date is 2020-12-04
- Start date is 2020-09-28

# Dotwin

## posts

In [1]:
import pandas as pd
import pyarrow
import matplotlib.pyplot as plt
import numpy as np

In [2]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-09-28')&(df1['timestamp'] <= '2020-12-05')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [3]:
a=df1.groupby('author',as_index=False).count()
a=a.drop(columns=["pid","data_id","timestamp","votes","upvotes","downvotes","title","title_link","content","image"])
a=a.rename(columns={"site":"#posts"})

In [4]:
a

                  author  #posts
0              14Kaner88       4
1              1stLssah1       1
2           4chon_dot_me       1
3                7pt5x55       1
4               APDSmith       2
..                   ...     ...
275        w-duranty6489       9
276              window5      21
277  xAzureAceStarburstx       4
278                xleb2       8
279               yitiat       1

[280 rows x 2 columns]

In [5]:
posts=a
posts

                  author  #posts
0              14Kaner88       4
1              1stLssah1       1
2           4chon_dot_me       1
3                7pt5x55       1
4               APDSmith       2
..                   ...     ...
275        w-duranty6489       9
276              window5      21
277  xAzureAceStarburstx       4
278                xleb2       8
279               yitiat       1

[280 rows x 2 columns]

In [6]:
posts["author"].is_unique

True

## comments

In [8]:
file_path="../largedata/dotwin/dotwin_comments.pkl"
df2=pd.read_pickle(file_path)
df2["timestamp"]=pd.to_datetime(df2["timestamp"])
df2= df2[(df2['timestamp'] >= '2020-09-28')&(df2['timestamp'] <= '2020-12-05')]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5
...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...

In [10]:
b=df2.groupby('author',as_index=False).count()
b=b.drop(columns=["pid","permalink","timestamp","upvotes","downvotes","content"])
b=b.rename(columns={"site":"#comments"})
b

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

In [11]:
b["author"].is_unique

True

In [12]:
comments=b
comments

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

## karma

In [13]:
df2["votes"]=df2["upvotes"]-df2["downvotes"]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content,votes
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...,5
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...,2
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...,4
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5,5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5,7
...,...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...,1
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.,4
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,5
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,4
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,4

In [14]:
df1["votes"]=df1["upvotes"]-df1["downvotes"]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [15]:
c=df2.groupby("author",as_index=False)["votes"].sum()
c

               author  votes
0    11numbereleven11     34
1           14Kaner88    165
2            17760704     25
3      1776ReasonsWhy      3
4             1badcop      3
..                ...    ...
774     xxxMAGA420xxx     85
775             yamez     39
776            yitiat     39
777             yoisi      5
778         zeuskabob      9

[779 rows x 2 columns]

In [16]:
c['votes'] = c['votes'].astype(float)
c

               author  votes
0    11numbereleven11   34.0
1           14Kaner88  165.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
774     xxxMAGA420xxx   85.0
775             yamez   39.0
776            yitiat   39.0
777             yoisi    5.0
778         zeuskabob    9.0

[779 rows x 2 columns]

In [17]:
d=df1.groupby("author",as_index=False)["votes"].sum()
d

                  author  votes
0              14Kaner88  121.0
1              1stLssah1   12.0
2           4chon_dot_me    4.0
3                7pt5x55   32.0
4               APDSmith   72.0
..                   ...    ...
275        w-duranty6489  367.0
276              window5  131.0
277  xAzureAceStarburstx  106.0
278                xleb2  352.0
279               yitiat   30.0

[280 rows x 2 columns]

In [18]:
e=pd.merge(c,d,on="author",how="outer",suffixes=("_c","_d"))
e=e.fillna(0.0)
e["karma"]=e["votes_c"]+e["votes_d"]
e

               author  votes_c  votes_d  karma
0    11numbereleven11     34.0      0.0   34.0
1           14Kaner88    165.0    121.0  286.0
2            17760704     25.0      0.0   25.0
3      1776ReasonsWhy      3.0      0.0    3.0
4             1badcop      3.0      0.0    3.0
..                ...      ...      ...    ...
838           soldier      0.0      4.0    4.0
839        someguy829      0.0     41.0   41.0
840           spiggot      0.0     33.0   33.0
841        temp342492      0.0     30.0   30.0
842      volcanonacho      0.0     25.0   25.0

[843 rows x 4 columns]

In [19]:
e["author"].is_unique

True

In [20]:
e=e.drop(columns=["votes_c","votes_d"])
e

               author  karma
0    11numbereleven11   34.0
1           14Kaner88  286.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
838           soldier    4.0
839        someguy829   41.0
840           spiggot   33.0
841        temp342492   30.0
842      volcanonacho   25.0

[843 rows x 2 columns]

In [21]:
e[e["karma"]<0]

                  author  karma
72   BlueGluePonchoVilla   -8.0
73            Bogmire777   -2.0
87   BubblesTheAnarchist   -3.0
114          CodeBlue_04   -4.0
299        Marcus_Garvey   -1.0
329       Nailgunsuicide  -59.0
365               Piroko -142.0
571       browarrior1950 -270.0
637             illannoy   -6.0
647         jobdestroyer   -4.0
801            Marklevin   -2.0
819        Unbound69nice   -3.0

## comments received

In [22]:
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content,votes
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...,5
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...,2
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...,4
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5,5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5,7
...,...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...,1
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.,4
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,5
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,4
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,4

In [23]:
comments

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

In [24]:
j=df2.groupby("pid",as_index=False).count()
j

,pid,site,permalink,timestamp,upvotes,downvotes,author,content,votes
0,11PVWGT77D,8,8,8,8,8,8,8,8
1,11PVWHdhcx,1,1,1,1,1,1,1,1
2,11PVWIkSBl,3,3,3,3,3,3,3,3
3,11PVWL2tFt,2,2,2,2,2,2,2,2
4,11PVWMABmS,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
809,HrhePjMG,1,1,1,1,1,1,1,1
810,HrhfYx5l,1,1,1,1,1,1,1,1
811,HrhhpkCR,2,2,2,2,2,2,2,2
812,Hrhixrbd,1,1,1,1,1,1,1,1
813,Hrhiyh1A,9,9,9,9,9,9,9,9

In [25]:
j=j.drop(columns=["permalink","timestamp","upvotes","downvotes","author","content","votes"])
j

            pid  site
0    11PVWGT77D     8
1    11PVWHdhcx     1
2    11PVWIkSBl     3
3    11PVWL2tFt     2
4    11PVWMABmS     1
..          ...   ...
809    HrhePjMG     1
810    HrhfYx5l     1
811    HrhhpkCR     2
812    Hrhixrbd     1
813    Hrhiyh1A     9

[814 rows x 2 columns]

In [26]:
j=j.rename(columns={"site":"comments"})
j

            pid  comments
0    11PVWGT77D         8
1    11PVWHdhcx         1
2    11PVWIkSBl         3
3    11PVWL2tFt         2
4    11PVWMABmS         1
..          ...       ...
809    HrhePjMG         1
810    HrhfYx5l         1
811    HrhhpkCR         2
812    Hrhixrbd         1
813    Hrhiyh1A         9

[814 rows x 2 columns]

In [27]:
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [28]:
ll=pd.merge(df1,j,on="pid",how="inner")
ll

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image,comments
0,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN,11
1,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...,2
2,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...,1
3,gavinmcinnes,HY2kZabb,855083.0,2020-09-28 10:59:01,4.0,5.0,1.0,4chon_dot_me,Someone on 4chon.me asked a question about Gav...,https://www.4chon.me/new/res/23028.html,NaN,NaN,1
4,gavinmcinnes,HY2kZrFq,855122.0,2020-09-28 11:10:59,5.0,6.0,1.0,Unclegisli,Jared Taylor,/p/HY2kZrFq/jared-taylor/,I'm looking for an episode of GOML with Jared ...,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,kotakuinaction2,11QlFibprQ,1442134.0,2020-12-04 18:43:49,40.0,42.0,2.0,AntonioOfVenice,Taylor Nichols: doctor's serial lies about tre...,https://imgur.com/gallery/6haMVq8,NaN,https://media.kotakuinaction2.win/preview/11Ql...,14
763,kotakuinaction2,11QlFie2aG,1442980.0,2020-12-04 20:24:00,47.0,47.0,0.0,RealDrJester,Georgia Ballots Being Pulled From Under The Ta...,https://youtu.be/uOU7X0CPFj0,NaN,https://media.kotakuinaction2.win/preview/11Ql...,3
764,kotakuinaction2,11QlFjmR2U,1443976.0,2020-12-04 22:20:21,46.0,49.0,3.0,xleb2,California politicians can’t explain their COV...,https://www.latimes.com/california/story/2020-...,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2
765,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN,3
766,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...,9

In [29]:
ll=ll.drop(columns=['site', 'data_id', 'timestamp', 'votes', 'upvotes', 'downvotes',
        'title', 'title_link', 'content','image'])
ll

            pid                author  comments
0      HY2iJtpK            scruffyusp        11
1      HY2jRSjY            salsashark         2
2      HY2jSYrc  the_real_friend0rags         1
3      HY2kZabb          4chon_dot_me         1
4      HY2kZrFq            Unclegisli         1
..          ...                   ...       ...
762  11QlFibprQ       AntonioOfVenice        14
763  11QlFie2aG          RealDrJester         3
764  11QlFjmR2U                 xleb2         2
765  11QlFktRyq        TheImpossible1         3
766  11QlFktSBM             kratomlol         9

[767 rows x 3 columns]

In [30]:
ll=ll.rename(columns={"comments":"comments_received"})
ll

            pid                author  comments_received
0      HY2iJtpK            scruffyusp                 11
1      HY2jRSjY            salsashark                  2
2      HY2jSYrc  the_real_friend0rags                  1
3      HY2kZabb          4chon_dot_me                  1
4      HY2kZrFq            Unclegisli                  1
..          ...                   ...                ...
762  11QlFibprQ       AntonioOfVenice                 14
763  11QlFie2aG          RealDrJester                  3
764  11QlFjmR2U                 xleb2                  2
765  11QlFktRyq        TheImpossible1                  3
766  11QlFktSBM             kratomlol                  9

[767 rows x 3 columns]

In [31]:
ll=ll.groupby("author",as_index=False)["comments_received"].sum()
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

In [32]:
ll["author"].is_unique

True

In [33]:
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

## role distribution

In [34]:
merged_df=pd.merge(posts,comments,on="author", how="outer")
merged_df

            author  #posts  #comments
0        14Kaner88     4.0       28.0
1        1stLssah1     1.0        2.0
2     4chon_dot_me     1.0        NaN
3          7pt5x55     1.0        NaN
4         APDSmith     2.0       39.0
..             ...     ...        ...
838   xdrunkagainx     NaN        1.0
839  xxxMAGA420xxx     NaN       16.0
840          yamez     NaN        5.0
841          yoisi     NaN        1.0
842      zeuskabob     NaN        4.0

[843 rows x 3 columns]

In [35]:
e

               author  karma
0    11numbereleven11   34.0
1           14Kaner88  286.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
838           soldier    4.0
839        someguy829   41.0
840           spiggot   33.0
841        temp342492   30.0
842      volcanonacho   25.0

[843 rows x 2 columns]

In [36]:
lv=pd.merge(merged_df,e,on="author",how="outer")
lv

            author  #posts  #comments  karma
0        14Kaner88     4.0       28.0  286.0
1        1stLssah1     1.0        2.0   14.0
2     4chon_dot_me     1.0        NaN    4.0
3          7pt5x55     1.0        NaN   32.0
4         APDSmith     2.0       39.0  558.0
..             ...     ...        ...    ...
838   xdrunkagainx     NaN        1.0    1.0
839  xxxMAGA420xxx     NaN       16.0   85.0
840          yamez     NaN        5.0   39.0
841          yoisi     NaN        1.0    5.0
842      zeuskabob     NaN        4.0    9.0

[843 rows x 4 columns]

In [37]:
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

In [38]:
tt=pd.merge(ll,lv,on="author",how="outer")
tt

            author  comments_received  #posts  #comments  karma
0        14Kaner88               48.0     4.0       28.0  286.0
1        1stLssah1                2.0     1.0        2.0   14.0
2     4chon_dot_me                1.0     1.0        NaN    4.0
3          7pt5x55                6.0     1.0        NaN   32.0
4         APDSmith               14.0     2.0       39.0  558.0
..             ...                ...     ...        ...    ...
838   xdrunkagainx                NaN     NaN        1.0    1.0
839  xxxMAGA420xxx                NaN     NaN       16.0   85.0
840          yamez                NaN     NaN        5.0   39.0
841          yoisi                NaN     NaN        1.0    5.0
842      zeuskabob                NaN     NaN        4.0    9.0

[843 rows x 5 columns]

In [39]:
tt["author"].is_unique

True