- This file has analysis with the range equivalent to Twitter
- Last date is 2020-12-04
- Start date is 2020-09-28

# Dotwin

## Role distribution

## posts

In [1]:
import pandas as pd
import pyarrow
import matplotlib.pyplot as plt
import numpy as np

In [2]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-09-28')&(df1['timestamp'] <= '2020-12-05')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [3]:
a=df1.groupby('author',as_index=False).count()
a=a.drop(columns=["pid","data_id","timestamp","votes","upvotes","downvotes","title","title_link","content","image"])
a=a.rename(columns={"site":"#posts"})

In [4]:
a

                  author  #posts
0              14Kaner88       4
1              1stLssah1       1
2           4chon_dot_me       1
3                7pt5x55       1
4               APDSmith       2
..                   ...     ...
275        w-duranty6489       9
276              window5      21
277  xAzureAceStarburstx       4
278                xleb2       8
279               yitiat       1

[280 rows x 2 columns]

In [5]:
posts=a
posts

                  author  #posts
0              14Kaner88       4
1              1stLssah1       1
2           4chon_dot_me       1
3                7pt5x55       1
4               APDSmith       2
..                   ...     ...
275        w-duranty6489       9
276              window5      21
277  xAzureAceStarburstx       4
278                xleb2       8
279               yitiat       1

[280 rows x 2 columns]

In [6]:
posts["author"].is_unique

True

## comments

In [8]:
file_path="../largedata/dotwin/dotwin_comments.pkl"
df2=pd.read_pickle(file_path)
df2["timestamp"]=pd.to_datetime(df2["timestamp"])
df2= df2[(df2['timestamp'] >= '2020-09-28')&(df2['timestamp'] <= '2020-12-05')]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5
...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...

In [10]:
b=df2.groupby('author',as_index=False).count()
b=b.drop(columns=["pid","permalink","timestamp","upvotes","downvotes","content"])
b=b.rename(columns={"site":"#comments"})
b

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

In [11]:
b["author"].is_unique

True

In [12]:
comments=b
comments

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

## karma

In [13]:
df2["votes"]=df2["upvotes"]-df2["downvotes"]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content,votes
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...,5
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...,2
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...,4
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5,5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5,7
...,...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...,1
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.,4
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,5
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,4
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,4

In [14]:
df1["votes"]=df1["upvotes"]-df1["downvotes"]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [15]:
c=df2.groupby("author",as_index=False)["votes"].sum()
c

               author  votes
0    11numbereleven11     34
1           14Kaner88    165
2            17760704     25
3      1776ReasonsWhy      3
4             1badcop      3
..                ...    ...
774     xxxMAGA420xxx     85
775             yamez     39
776            yitiat     39
777             yoisi      5
778         zeuskabob      9

[779 rows x 2 columns]

In [16]:
c['votes'] = c['votes'].astype(float)
c

               author  votes
0    11numbereleven11   34.0
1           14Kaner88  165.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
774     xxxMAGA420xxx   85.0
775             yamez   39.0
776            yitiat   39.0
777             yoisi    5.0
778         zeuskabob    9.0

[779 rows x 2 columns]

In [17]:
d=df1.groupby("author",as_index=False)["votes"].sum()
d

                  author  votes
0              14Kaner88  121.0
1              1stLssah1   12.0
2           4chon_dot_me    4.0
3                7pt5x55   32.0
4               APDSmith   72.0
..                   ...    ...
275        w-duranty6489  367.0
276              window5  131.0
277  xAzureAceStarburstx  106.0
278                xleb2  352.0
279               yitiat   30.0

[280 rows x 2 columns]

In [18]:
e=pd.merge(c,d,on="author",how="outer",suffixes=("_c","_d"))
e=e.fillna(0.0)
e["karma"]=e["votes_c"]+e["votes_d"]
e

               author  votes_c  votes_d  karma
0    11numbereleven11     34.0      0.0   34.0
1           14Kaner88    165.0    121.0  286.0
2            17760704     25.0      0.0   25.0
3      1776ReasonsWhy      3.0      0.0    3.0
4             1badcop      3.0      0.0    3.0
..                ...      ...      ...    ...
838           soldier      0.0      4.0    4.0
839        someguy829      0.0     41.0   41.0
840           spiggot      0.0     33.0   33.0
841        temp342492      0.0     30.0   30.0
842      volcanonacho      0.0     25.0   25.0

[843 rows x 4 columns]

In [19]:
e["author"].is_unique

True

In [20]:
e=e.drop(columns=["votes_c","votes_d"])
e

               author  karma
0    11numbereleven11   34.0
1           14Kaner88  286.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
838           soldier    4.0
839        someguy829   41.0
840           spiggot   33.0
841        temp342492   30.0
842      volcanonacho   25.0

[843 rows x 2 columns]

In [21]:
e[e["karma"]<0]

                  author  karma
72   BlueGluePonchoVilla   -8.0
73            Bogmire777   -2.0
87   BubblesTheAnarchist   -3.0
114          CodeBlue_04   -4.0
299        Marcus_Garvey   -1.0
329       Nailgunsuicide  -59.0
365               Piroko -142.0
571       browarrior1950 -270.0
637             illannoy   -6.0
647         jobdestroyer   -4.0
801            Marklevin   -2.0
819        Unbound69nice   -3.0

## comments received

In [22]:
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content,votes
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...,5
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...,2
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...,4
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5,5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5,7
...,...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...,1
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.,4
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,5
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,4
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,4

In [23]:
comments

               author  #comments
0    11numbereleven11          3
1           14Kaner88         28
2            17760704          5
3      1776ReasonsWhy          1
4             1badcop          1
..                ...        ...
774     xxxMAGA420xxx         16
775             yamez          5
776            yitiat          3
777             yoisi          1
778         zeuskabob          4

[779 rows x 2 columns]

In [24]:
j=df2.groupby("pid",as_index=False).count()
j

,pid,site,permalink,timestamp,upvotes,downvotes,author,content,votes
0,11PVWGT77D,8,8,8,8,8,8,8,8
1,11PVWHdhcx,1,1,1,1,1,1,1,1
2,11PVWIkSBl,3,3,3,3,3,3,3,3
3,11PVWL2tFt,2,2,2,2,2,2,2,2
4,11PVWMABmS,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
809,HrhePjMG,1,1,1,1,1,1,1,1
810,HrhfYx5l,1,1,1,1,1,1,1,1
811,HrhhpkCR,2,2,2,2,2,2,2,2
812,Hrhixrbd,1,1,1,1,1,1,1,1
813,Hrhiyh1A,9,9,9,9,9,9,9,9

In [25]:
j=j.drop(columns=["permalink","timestamp","upvotes","downvotes","author","content","votes"])
j

            pid  site
0    11PVWGT77D     8
1    11PVWHdhcx     1
2    11PVWIkSBl     3
3    11PVWL2tFt     2
4    11PVWMABmS     1
..          ...   ...
809    HrhePjMG     1
810    HrhfYx5l     1
811    HrhhpkCR     2
812    Hrhixrbd     1
813    Hrhiyh1A     9

[814 rows x 2 columns]

In [26]:
j=j.rename(columns={"site":"comments"})
j

            pid  comments
0    11PVWGT77D         8
1    11PVWHdhcx         1
2    11PVWIkSBl         3
3    11PVWL2tFt         2
4    11PVWMABmS         1
..          ...       ...
809    HrhePjMG         1
810    HrhfYx5l         1
811    HrhhpkCR         2
812    Hrhixrbd         1
813    Hrhiyh1A         9

[814 rows x 2 columns]

In [27]:
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [28]:
ll=pd.merge(df1,j,on="pid",how="inner")
ll

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image,comments
0,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN,11
1,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...,2
2,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...,1
3,gavinmcinnes,HY2kZabb,855083.0,2020-09-28 10:59:01,4.0,5.0,1.0,4chon_dot_me,Someone on 4chon.me asked a question about Gav...,https://www.4chon.me/new/res/23028.html,NaN,NaN,1
4,gavinmcinnes,HY2kZrFq,855122.0,2020-09-28 11:10:59,5.0,6.0,1.0,Unclegisli,Jared Taylor,/p/HY2kZrFq/jared-taylor/,I'm looking for an episode of GOML with Jared ...,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,kotakuinaction2,11QlFibprQ,1442134.0,2020-12-04 18:43:49,40.0,42.0,2.0,AntonioOfVenice,Taylor Nichols: doctor's serial lies about tre...,https://imgur.com/gallery/6haMVq8,NaN,https://media.kotakuinaction2.win/preview/11Ql...,14
763,kotakuinaction2,11QlFie2aG,1442980.0,2020-12-04 20:24:00,47.0,47.0,0.0,RealDrJester,Georgia Ballots Being Pulled From Under The Ta...,https://youtu.be/uOU7X0CPFj0,NaN,https://media.kotakuinaction2.win/preview/11Ql...,3
764,kotakuinaction2,11QlFjmR2U,1443976.0,2020-12-04 22:20:21,46.0,49.0,3.0,xleb2,California politicians can’t explain their COV...,https://www.latimes.com/california/story/2020-...,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2
765,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN,3
766,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...,9

In [29]:
ll=ll.drop(columns=['site', 'data_id', 'timestamp', 'votes', 'upvotes', 'downvotes',
        'title', 'title_link', 'content','image'])
ll

            pid                author  comments
0      HY2iJtpK            scruffyusp        11
1      HY2jRSjY            salsashark         2
2      HY2jSYrc  the_real_friend0rags         1
3      HY2kZabb          4chon_dot_me         1
4      HY2kZrFq            Unclegisli         1
..          ...                   ...       ...
762  11QlFibprQ       AntonioOfVenice        14
763  11QlFie2aG          RealDrJester         3
764  11QlFjmR2U                 xleb2         2
765  11QlFktRyq        TheImpossible1         3
766  11QlFktSBM             kratomlol         9

[767 rows x 3 columns]

In [30]:
ll=ll.rename(columns={"comments":"comments_received"})
ll

            pid                author  comments_received
0      HY2iJtpK            scruffyusp                 11
1      HY2jRSjY            salsashark                  2
2      HY2jSYrc  the_real_friend0rags                  1
3      HY2kZabb          4chon_dot_me                  1
4      HY2kZrFq            Unclegisli                  1
..          ...                   ...                ...
762  11QlFibprQ       AntonioOfVenice                 14
763  11QlFie2aG          RealDrJester                  3
764  11QlFjmR2U                 xleb2                  2
765  11QlFktRyq        TheImpossible1                  3
766  11QlFktSBM             kratomlol                  9

[767 rows x 3 columns]

In [31]:
ll=ll.groupby("author",as_index=False)["comments_received"].sum()
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

In [32]:
ll["author"].is_unique

True

In [33]:
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

## role distribution

In [34]:
merged_df=pd.merge(posts,comments,on="author", how="outer")
merged_df

            author  #posts  #comments
0        14Kaner88     4.0       28.0
1        1stLssah1     1.0        2.0
2     4chon_dot_me     1.0        NaN
3          7pt5x55     1.0        NaN
4         APDSmith     2.0       39.0
..             ...     ...        ...
838   xdrunkagainx     NaN        1.0
839  xxxMAGA420xxx     NaN       16.0
840          yamez     NaN        5.0
841          yoisi     NaN        1.0
842      zeuskabob     NaN        4.0

[843 rows x 3 columns]

In [35]:
e

               author  karma
0    11numbereleven11   34.0
1           14Kaner88  286.0
2            17760704   25.0
3      1776ReasonsWhy    3.0
4             1badcop    3.0
..                ...    ...
838           soldier    4.0
839        someguy829   41.0
840           spiggot   33.0
841        temp342492   30.0
842      volcanonacho   25.0

[843 rows x 2 columns]

In [36]:
lv=pd.merge(merged_df,e,on="author",how="outer")
lv

            author  #posts  #comments  karma
0        14Kaner88     4.0       28.0  286.0
1        1stLssah1     1.0        2.0   14.0
2     4chon_dot_me     1.0        NaN    4.0
3          7pt5x55     1.0        NaN   32.0
4         APDSmith     2.0       39.0  558.0
..             ...     ...        ...    ...
838   xdrunkagainx     NaN        1.0    1.0
839  xxxMAGA420xxx     NaN       16.0   85.0
840          yamez     NaN        5.0   39.0
841          yoisi     NaN        1.0    5.0
842      zeuskabob     NaN        4.0    9.0

[843 rows x 4 columns]

In [37]:
ll

                  author  comments_received
0              14Kaner88                 48
1              1stLssah1                  2
2           4chon_dot_me                  1
3                7pt5x55                  6
4               APDSmith                 14
..                   ...                ...
254        w-duranty6489                 69
255              window5                 32
256  xAzureAceStarburstx                  8
257                xleb2                 55
258               yitiat                 17

[259 rows x 2 columns]

In [38]:
tt=pd.merge(ll,lv,on="author",how="outer")
tt

            author  comments_received  #posts  #comments  karma
0        14Kaner88               48.0     4.0       28.0  286.0
1        1stLssah1                2.0     1.0        2.0   14.0
2     4chon_dot_me                1.0     1.0        NaN    4.0
3          7pt5x55                6.0     1.0        NaN   32.0
4         APDSmith               14.0     2.0       39.0  558.0
..             ...                ...     ...        ...    ...
838   xdrunkagainx                NaN     NaN        1.0    1.0
839  xxxMAGA420xxx                NaN     NaN       16.0   85.0
840          yamez                NaN     NaN        5.0   39.0
841          yoisi                NaN     NaN        1.0    5.0
842      zeuskabob                NaN     NaN        4.0    9.0

[843 rows x 5 columns]

In [39]:
tt["author"].is_unique

True

In [40]:
final_df=tt
final_df

            author  comments_received  #posts  #comments  karma
0        14Kaner88               48.0     4.0       28.0  286.0
1        1stLssah1                2.0     1.0        2.0   14.0
2     4chon_dot_me                1.0     1.0        NaN    4.0
3          7pt5x55                6.0     1.0        NaN   32.0
4         APDSmith               14.0     2.0       39.0  558.0
..             ...                ...     ...        ...    ...
838   xdrunkagainx                NaN     NaN        1.0    1.0
839  xxxMAGA420xxx                NaN     NaN       16.0   85.0
840          yamez                NaN     NaN        5.0   39.0
841          yoisi                NaN     NaN        1.0    5.0
842      zeuskabob                NaN     NaN        4.0    9.0

[843 rows x 5 columns]

## imputing

In [45]:
final_df=tt
final_df

            author  comments_received  #posts  #comments  karma
0        14Kaner88               48.0    28.0       28.0  286.0
1        1stLssah1                2.0     2.0        2.0   14.0
2     4chon_dot_me                1.0     0.0        NaN    4.0
3          7pt5x55                6.0     0.0        NaN   32.0
4         APDSmith               14.0    39.0       39.0  558.0
..             ...                ...     ...        ...    ...
838   xdrunkagainx                NaN     1.0        1.0    1.0
839  xxxMAGA420xxx                NaN    16.0       16.0   85.0
840          yamez                NaN     5.0        5.0   39.0
841          yoisi                NaN     1.0        1.0    5.0
842      zeuskabob                NaN     4.0        4.0    9.0

[843 rows x 5 columns]

In [46]:
final_df["#posts"]=final_df["#posts"].fillna(0)

In [47]:
final_df["#comments"]=final_df["#comments"].fillna(0)

In [48]:
final_df["karma"]=final_df["karma"].fillna(0)

In [49]:
final_df["comments_received"]=final_df["comments_received"].fillna(0)

In [50]:
final_df

            author  comments_received  #posts  #comments  karma
0        14Kaner88               48.0    28.0       28.0  286.0
1        1stLssah1                2.0     2.0        2.0   14.0
2     4chon_dot_me                1.0     0.0        0.0    4.0
3          7pt5x55                6.0     0.0        0.0   32.0
4         APDSmith               14.0    39.0       39.0  558.0
..             ...                ...     ...        ...    ...
838   xdrunkagainx                0.0     1.0        1.0    1.0
839  xxxMAGA420xxx                0.0    16.0       16.0   85.0
840          yamez                0.0     5.0        5.0   39.0
841          yoisi                0.0     1.0        1.0    5.0
842      zeuskabob                0.0     4.0        4.0    9.0

[843 rows x 5 columns]

In [51]:
final_df["ratio_#comments_karma"]=final_df["#comments"]/final_df["karma"]
final_df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma
0,14Kaner88,48.0,28.0,28.0,286.0,0.097902
1,1stLssah1,2.0,2.0,2.0,14.0,0.142857
2,4chon_dot_me,1.0,0.0,0.0,4.0,0.000000
3,7pt5x55,6.0,0.0,0.0,32.0,0.000000
4,APDSmith,14.0,39.0,39.0,558.0,0.069892
...,...,...,...,...,...,...
838,xdrunkagainx,0.0,1.0,1.0,1.0,1.000000
839,xxxMAGA420xxx,0.0,16.0,16.0,85.0,0.188235
840,yamez,0.0,5.0,5.0,39.0,0.128205
841,yoisi,0.0,1.0,1.0,5.0,0.200000
842,zeuskabob,0.0,4.0,4.0,9.0,0.444444

In [52]:
final_df["ratio_comments_received_#posts"]=final_df["comments_received"]/final_df["#posts"]
final_df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,14Kaner88,48.0,28.0,28.0,286.0,0.097902,1.714286
1,1stLssah1,2.0,2.0,2.0,14.0,0.142857,1.000000
2,4chon_dot_me,1.0,0.0,0.0,4.0,0.000000,inf
3,7pt5x55,6.0,0.0,0.0,32.0,0.000000,inf
4,APDSmith,14.0,39.0,39.0,558.0,0.069892,0.358974
...,...,...,...,...,...,...,...
838,xdrunkagainx,0.0,1.0,1.0,1.0,1.000000,0.000000
839,xxxMAGA420xxx,0.0,16.0,16.0,85.0,0.188235,0.000000
840,yamez,0.0,5.0,5.0,39.0,0.128205,0.000000
841,yoisi,0.0,1.0,1.0,5.0,0.200000,0.000000
842,zeuskabob,0.0,4.0,4.0,9.0,0.444444,0.000000

In [53]:
import numpy as np
columns_to_check = ["ratio_#comments_karma","ratio_comments_received_#posts","comments_received","#posts","#comments","karma"]

for column in columns_to_check:
    if np.isinf(final_df[column]).any():
        print(f"Column {column} contains infinite values")


for column in columns_to_check:
    zero_count = (final_df[column] == 0).sum()
    if zero_count > 0:
        print(f"Column {column} contains {zero_count} zero values")

for column in columns_to_check:
    nan_count = final_df[column].isna().sum()
    if nan_count > 0:
        print(f"Column {column} contains {nan_count} NaN values")

for column in columns_to_check:
    negative = final_df[column]<0
    a=negative.sum()
    print(f"Column {column} contains {a} negative values")

Column ratio_#comments_karma contains infinite values
Column ratio_comments_received_#posts contains infinite values
Column ratio_#comments_karma contains 60 zero values
Column ratio_comments_received_#posts contains 571 zero values
Column comments_received contains 584 zero values
Column #posts contains 64 zero values
Column #comments contains 64 zero values
Column karma contains 7 zero values
Column ratio_#comments_karma contains 4 NaN values
Column ratio_comments_received_#posts contains 13 NaN values
Column ratio_#comments_karma contains 10 negative values
Column ratio_comments_received_#posts contains 0 negative values
Column comments_received contains 0 negative values
Column #posts contains 0 negative values
Column #comments contains 0 negative values
Column karma contains 12 negative values

In [54]:
final_df[final_df["ratio_#comments_karma"].isna()]

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
58,GB97,1.0,0.0,0.0,0.0,NaN,inf
237,shadypollster,1.0,0.0,0.0,0.0,NaN,inf
259,AgentChen,0.0,0.0,0.0,0.0,NaN,NaN
279,iceposeidonip2ip2ip2,0.0,0.0,0.0,0.0,NaN,NaN

In [55]:
final_df[final_df["ratio_comments_received_#posts"].isna()]

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
259,AgentChen,0.0,0.0,0.0,0.0,NaN,NaN
261,Comatoast,0.0,0.0,0.0,5.0,0.0,NaN
262,DrHereCanConfirm,0.0,0.0,0.0,1.0,0.0,NaN
263,Freddiebeansno1fan,0.0,0.0,0.0,3.0,0.0,NaN
266,Jagkag,0.0,0.0,0.0,10.0,0.0,NaN
270,Phreedom,0.0,0.0,0.0,14.0,0.0,NaN
272,The_Matrix_Kid,0.0,0.0,0.0,13.0,0.0,NaN
274,ampersandyandy,0.0,0.0,0.0,10.0,0.0,NaN
275,antiantifa45,0.0,0.0,0.0,7.0,0.0,NaN
276,dream123,0.0,0.0,0.0,9.0,0.0,NaN
277,happywar,0.0,0.0,0.0,12.0,0.0,NaN
278,hotrodcamry,0.0,0.0,0.0,6.0,0.0,NaN
279,iceposeidonip2ip2ip2,0.0,0.0,0.0,0.0,NaN,NaN

In [56]:
final_df["ratio_#comments_karma"]=final_df["ratio_#comments_karma"].fillna(1.0)

In [57]:
final_df["ratio_comments_received_#posts"]=final_df["ratio_comments_received_#posts"].fillna(1.0)

In [63]:
import numpy as np
columns_to_check = ["ratio_#comments_karma","ratio_comments_received_#posts","comments_received","#posts","#comments","karma"]

for column in columns_to_check:
    if np.isinf(final_df[column]).any():
        print(f"Column {column} contains infinite values")


for column in columns_to_check:
    zero_count = (final_df[column] == 0).sum()
    if zero_count > 0:
        print(f"Column {column} contains {zero_count} zero values")

for column in columns_to_check:
    nan_count = final_df[column].isna().sum()
    if nan_count > 0:
        print(f"Column {column} contains {nan_count} NaN values")

for column in columns_to_check:
    negative = final_df[column]<0
    a=negative.sum()
    print(f"Column {column} contains {a} negative values")

Column ratio_#comments_karma contains infinite values
Column ratio_comments_received_#posts contains infinite values
Column ratio_#comments_karma contains 60 zero values
Column ratio_comments_received_#posts contains 571 zero values
Column comments_received contains 584 zero values
Column #posts contains 64 zero values
Column #comments contains 64 zero values
Column karma contains 7 zero values
Column ratio_#comments_karma contains 10 negative values
Column ratio_comments_received_#posts contains 0 negative values
Column comments_received contains 0 negative values
Column #posts contains 0 negative values
Column #comments contains 0 negative values
Column karma contains 12 negative values

In [58]:
final_df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,14Kaner88,48.0,28.0,28.0,286.0,0.097902,1.714286
1,1stLssah1,2.0,2.0,2.0,14.0,0.142857,1.000000
2,4chon_dot_me,1.0,0.0,0.0,4.0,0.000000,inf
3,7pt5x55,6.0,0.0,0.0,32.0,0.000000,inf
4,APDSmith,14.0,39.0,39.0,558.0,0.069892,0.358974
...,...,...,...,...,...,...,...
838,xdrunkagainx,0.0,1.0,1.0,1.0,1.000000,0.000000
839,xxxMAGA420xxx,0.0,16.0,16.0,85.0,0.188235,0.000000
840,yamez,0.0,5.0,5.0,39.0,0.128205,0.000000
841,yoisi,0.0,1.0,1.0,5.0,0.200000,0.000000
842,zeuskabob,0.0,4.0,4.0,9.0,0.444444,0.000000

## roles

In [59]:
broadcaster=(final_df["ratio_#comments_karma"]<1)&(final_df["ratio_comments_received_#posts"]<1)
broadcaster.sum()

584

In [68]:
584/776*100

75.25773195876289

In [60]:
common_users=(final_df["ratio_#comments_karma"]>1)&(final_df["ratio_comments_received_#posts"]<1)
common_users.sum()

3

In [69]:
3/776*100

0.3865979381443299

In [61]:
hidden_influentials=(final_df["ratio_#comments_karma"]>1)&(final_df["ratio_comments_received_#posts"]>1)
hidden_influentials.sum()

0

In [70]:
0

0

In [62]:
influentials=(final_df["ratio_#comments_karma"]<1)&(final_df["ratio_comments_received_#posts"]>1)
influentials.sum()

174

In [71]:
174/776*100

22.422680412371136

In [64]:
lurker=(final_df["ratio_#comments_karma"]==1)|(final_df["ratio_comments_received_#posts"]==1)
lurker.sum()

82

In [65]:
584+3+0+174+82

843

In [66]:
new_lurkers=(((final_df["#comments"]==0)&(final_df["karma"]==0))|((final_df["#posts"]==0)&(final_df["comments_received"]==0)))
new_lurkers.sum()

15

In [72]:
15/776*100

1.9329896907216495

In [67]:
total=843-82+15
total

776

- This includes people who have the ratio of both metric as one but have actual value, ex: posts=2 and comments_received=2

## Week analysis

### Posts

In [75]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-09-28')&(df1['timestamp'] <= '2020-12-05')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [77]:
df1['year_week'] = df1['timestamp'].dt.to_period('W')
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image,year_week
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN,2020-09-28/2020-10-04
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...,2020-09-28/2020-10-04
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...,2020-09-28/2020-10-04
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...,2020-09-28/2020-10-04
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...,2020-09-28/2020-10-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2020-11-30/2020-12-06
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN,2020-11-30/2020-12-06
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2020-11-30/2020-12-06
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2020-11-30/2020-12-06
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...,2020-11-30/2020-12-06

In [78]:
df1=df1[["author","title","year_week","content"]]
df1

,author,title,year_week,content
1225,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1226,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
1227,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
1228,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
1229,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
2205,Phreedom,Merry Wokemas!,2020-11-30/2020-12-06,NaN
2206,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,2020-11-30/2020-12-06,NaN
2207,kratomlol,I hope she gives a speech on women empowerment...,2020-11-30/2020-12-06,NaN
2208,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,2020-11-30/2020-12-06,NaN
2209,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,2020-11-30/2020-12-06,NaN

In [95]:
unique_posts_week = df1.groupby('year_week').size().reset_index(name='count')
unique_posts_week

               year_week  count
0  2020-09-28/2020-10-04    119
1  2020-10-05/2020-10-11     91
2  2020-10-12/2020-10-18     88
3  2020-10-19/2020-10-25     86
4  2020-10-26/2020-11-01     67
5  2020-11-02/2020-11-08     84
6  2020-11-09/2020-11-15     68
7  2020-11-16/2020-11-22     47
8  2020-11-23/2020-11-29    206
9  2020-11-30/2020-12-06    129

In [96]:
unique_posts_week["count"].sum()

985

In [97]:
unique_posts_week["count"]=unique_posts_week["count"]/985

In [98]:
unique_posts_week["count"]=unique_posts_week["count"]*100
unique_posts_week

               year_week      count
0  2020-09-28/2020-10-04  12.081218
1  2020-10-05/2020-10-11   9.238579
2  2020-10-12/2020-10-18   8.934010
3  2020-10-19/2020-10-25   8.730964
4  2020-10-26/2020-11-01   6.802030
5  2020-11-02/2020-11-08   8.527919
6  2020-11-09/2020-11-15   6.903553
7  2020-11-16/2020-11-22   4.771574
8  2020-11-23/2020-11-29  20.913706
9  2020-11-30/2020-12-06  13.096447

In [99]:
unique_posts_week["count"].sum()

100.0

### comments

In [76]:
file_path="../largedata/dotwin/dotwin_comments.pkl"
df2=pd.read_pickle(file_path)
df2["timestamp"]=pd.to_datetime(df2["timestamp"])
df2= df2[(df2['timestamp'] >= '2020-09-28')&(df2['timestamp'] <= '2020-12-05')]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5
...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...

In [79]:
df2['year_week'] = df2['timestamp'].dt.to_period('W')
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content,year_week
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...,2020-09-28/2020-10-04
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...,2020-09-28/2020-10-04
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...,2020-09-28/2020-10-04
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5,2020-09-28/2020-10-04
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5,2020-09-28/2020-10-04
...,...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...,2020-11-30/2020-12-06
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.,2020-11-30/2020-12-06
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,2020-11-30/2020-12-06
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,2020-11-30/2020-12-06
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,2020-11-30/2020-12-06

In [80]:
df2=df2[["author","content","year_week"]]
df2

,author,content,year_week
8423,scruffyusp,I'm down so long as automatics are cool too.\n...,2020-09-28/2020-10-04
8424,julyspy,I am into strong tall girls. I just think of t...,2020-09-28/2020-10-04
8425,Hillary_is_Satan,That guy about halfway though the vid had a YU...,2020-09-28/2020-10-04
8426,Geralt_of_Rivia1,11.5,2020-09-28/2020-10-04
8427,Kappa,12.5,2020-09-28/2020-10-04
...,...,...,...
14912,Liberatevia300AAC,A stripper is always single if you throw enoug...,2020-11-30/2020-12-06
14913,TheImpossible1,MSM settled to avoid discovery.,2020-11-30/2020-12-06
14914,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,2020-11-30/2020-12-06
14915,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,2020-11-30/2020-12-06
14916,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,2020-11-30/2020-12-06

In [86]:
week_counts_co = df2.groupby('year_week').size()

In [87]:
week_counts_co

year_week
2020-09-28/2020-10-04     500
2020-10-05/2020-10-11     348
2020-10-12/2020-10-18     306
2020-10-19/2020-10-25     260
2020-10-26/2020-11-01     250
2020-11-02/2020-11-08     569
2020-11-09/2020-11-15     411
2020-11-16/2020-11-22     362
2020-11-23/2020-11-29    2070
2020-11-30/2020-12-06    1418
Freq: W-SUN, dtype: int64

In [88]:
week_counts_df2 = week_counts_co.reset_index(name='row_count')
week_counts_df2

               year_week  row_count
0  2020-09-28/2020-10-04        500
1  2020-10-05/2020-10-11        348
2  2020-10-12/2020-10-18        306
3  2020-10-19/2020-10-25        260
4  2020-10-26/2020-11-01        250
5  2020-11-02/2020-11-08        569
6  2020-11-09/2020-11-15        411
7  2020-11-16/2020-11-22        362
8  2020-11-23/2020-11-29       2070
9  2020-11-30/2020-12-06       1418

In [89]:
week_counts_df2["row_count"].sum()

6494

In [90]:
week_counts_df2["row_count"]=week_counts_df2["row_count"]/6494

In [91]:
week_counts_df2

               year_week  row_count
0  2020-09-28/2020-10-04   0.076994
1  2020-10-05/2020-10-11   0.053588
2  2020-10-12/2020-10-18   0.047120
3  2020-10-19/2020-10-25   0.040037
4  2020-10-26/2020-11-01   0.038497
5  2020-11-02/2020-11-08   0.087619
6  2020-11-09/2020-11-15   0.063289
7  2020-11-16/2020-11-22   0.055744
8  2020-11-23/2020-11-29   0.318756
9  2020-11-30/2020-12-06   0.218355

In [93]:
week_counts_df2["row_count"]=week_counts_df2["row_count"]*100
week_counts_df2

               year_week  row_count
0  2020-09-28/2020-10-04   7.699415
1  2020-10-05/2020-10-11   5.358793
2  2020-10-12/2020-10-18   4.712042
3  2020-10-19/2020-10-25   4.003696
4  2020-10-26/2020-11-01   3.849707
5  2020-11-02/2020-11-08   8.761934
6  2020-11-09/2020-11-15   6.328919
7  2020-11-16/2020-11-22   5.574376
8  2020-11-23/2020-11-29  31.875577
9  2020-11-30/2020-12-06  21.835540

In [94]:
week_counts_df2["row_count"].sum()

100.0

### users

In [81]:
concatenated_df = pd.concat([df1,df2], axis=0)
concatenated_df

,author,title,year_week,content
1225,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1226,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
1227,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
1228,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
1229,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
14912,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,A stripper is always single if you throw enoug...
14913,TheImpossible1,NaN,2020-11-30/2020-12-06,MSM settled to avoid discovery.
14914,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,These do not spark joy.\nAnd by joy I mean ere...
14915,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,What a stupid fucking comment she’s clearly a ...
14916,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,In fact someone find photos of her poosi I wan...

In [82]:
concatenated_df["author"].nunique()

843

In [83]:
unique_authors_per_week = concatenated_df.groupby('year_week')['author'].nunique()
unique_authors_df = unique_authors_per_week.reset_index(name='unique_authors')
unique_authors_df

               year_week  unique_authors
0  2020-09-28/2020-10-04             168
1  2020-10-05/2020-10-11             136
2  2020-10-12/2020-10-18             118
3  2020-10-19/2020-10-25             114
4  2020-10-26/2020-11-01             107
5  2020-11-02/2020-11-08             179
6  2020-11-09/2020-11-15             158
7  2020-11-16/2020-11-22             127
8  2020-11-23/2020-11-29             340
9  2020-11-30/2020-12-06             276

In [84]:
unique_authors_df["unique_authors"]=(unique_authors_df["unique_authors"]/843)*100

In [85]:
unique_authors_df

               year_week  unique_authors
0  2020-09-28/2020-10-04       19.928826
1  2020-10-05/2020-10-11       16.132859
2  2020-10-12/2020-10-18       13.997628
3  2020-10-19/2020-10-25       13.523132
4  2020-10-26/2020-11-01       12.692764
5  2020-11-02/2020-11-08       21.233689
6  2020-11-09/2020-11-15       18.742586
7  2020-11-16/2020-11-22       15.065243
8  2020-11-23/2020-11-29       40.332147
9  2020-11-30/2020-12-06       32.740214

- We can see peak around end of November 2020

## Persistence

## Posts

In [100]:
df1

,author,title,year_week,content
1225,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1226,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
1227,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
1228,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
1229,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
2205,Phreedom,Merry Wokemas!,2020-11-30/2020-12-06,NaN
2206,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,2020-11-30/2020-12-06,NaN
2207,kratomlol,I hope she gives a speech on women empowerment...,2020-11-30/2020-12-06,NaN
2208,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,2020-11-30/2020-12-06,NaN
2209,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,2020-11-30/2020-12-06,NaN

In [102]:
grouped = df1.groupby(['author', 'year_week']).size().reset_index(name='count')
grouped

                  author              year_week  count
0              14Kaner88  2020-10-19/2020-10-25      1
1              14Kaner88  2020-10-26/2020-11-01      1
2              14Kaner88  2020-11-09/2020-11-15      1
3              14Kaner88  2020-11-30/2020-12-06      1
4              1stLssah1  2020-11-09/2020-11-15      1
..                   ...                    ...    ...
495              window5  2020-11-23/2020-11-29      1
496  xAzureAceStarburstx  2020-11-23/2020-11-29      4
497                xleb2  2020-11-23/2020-11-29      5
498                xleb2  2020-11-30/2020-12-06      3
499               yitiat  2020-11-23/2020-11-29      1

[500 rows x 3 columns]

In [104]:
vf=df1.groupby('author')['year_week'].nunique().reset_index(name='weeks_active')
vf

                  author  weeks_active
0              14Kaner88             4
1              1stLssah1             1
2           4chon_dot_me             1
3                7pt5x55             1
4               APDSmith             1
..                   ...           ...
275        w-duranty6489             1
276              window5             7
277  xAzureAceStarburstx             1
278                xleb2             2
279               yitiat             1

[280 rows x 2 columns]

In [105]:
vf["author"].is_unique

True

In [106]:
d=vf["weeks_active"].value_counts().sort_index()
d

1    188
2     50
3     14
4      7
5      4
6      7
7      4
8      2
9      4
Name: weeks_active, dtype: int64

## Comments

In [107]:
df2

,author,content,year_week
8423,scruffyusp,I'm down so long as automatics are cool too.\n...,2020-09-28/2020-10-04
8424,julyspy,I am into strong tall girls. I just think of t...,2020-09-28/2020-10-04
8425,Hillary_is_Satan,That guy about halfway though the vid had a YU...,2020-09-28/2020-10-04
8426,Geralt_of_Rivia1,11.5,2020-09-28/2020-10-04
8427,Kappa,12.5,2020-09-28/2020-10-04
...,...,...,...
14912,Liberatevia300AAC,A stripper is always single if you throw enoug...,2020-11-30/2020-12-06
14913,TheImpossible1,MSM settled to avoid discovery.,2020-11-30/2020-12-06
14914,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,2020-11-30/2020-12-06
14915,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,2020-11-30/2020-12-06
14916,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,2020-11-30/2020-12-06

In [108]:
grouped_df = df2.groupby(['author', 'year_week']).size().reset_index(name='count')
grouped_df

                author              year_week  count
0     11numbereleven11  2020-11-23/2020-11-29      2
1     11numbereleven11  2020-11-30/2020-12-06      1
2            14Kaner88  2020-09-28/2020-10-04      5
3            14Kaner88  2020-10-05/2020-10-11      1
4            14Kaner88  2020-10-12/2020-10-18      2
...                ...                    ...    ...
1565             yamez  2020-11-23/2020-11-29      2
1566             yamez  2020-11-30/2020-12-06      3
1567            yitiat  2020-11-23/2020-11-29      3
1568             yoisi  2020-11-23/2020-11-29      1
1569         zeuskabob  2020-11-30/2020-12-06      4

[1570 rows x 3 columns]

In [110]:
vv=df2.groupby('author')['year_week'].nunique().reset_index(name='weeks_active')
vv

               author  weeks_active
0    11numbereleven11             2
1           14Kaner88             9
2            17760704             3
3      1776ReasonsWhy             1
4             1badcop             1
..                ...           ...
774     xxxMAGA420xxx             5
775             yamez             2
776            yitiat             1
777             yoisi             1
778         zeuskabob             1

[779 rows x 2 columns]

In [111]:
d=vv["weeks_active"].value_counts().sort_index()
d

1     436
2     198
3      51
4      24
5      24
6       8
7       7
8      12
9      14
10      5
Name: weeks_active, dtype: int64

## Users

In [112]:
df1

,author,title,year_week,content
1225,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1226,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
1227,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
1228,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
1229,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
2205,Phreedom,Merry Wokemas!,2020-11-30/2020-12-06,NaN
2206,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,2020-11-30/2020-12-06,NaN
2207,kratomlol,I hope she gives a speech on women empowerment...,2020-11-30/2020-12-06,NaN
2208,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,2020-11-30/2020-12-06,NaN
2209,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,2020-11-30/2020-12-06,NaN

In [113]:
df2

,author,content,year_week
8423,scruffyusp,I'm down so long as automatics are cool too.\n...,2020-09-28/2020-10-04
8424,julyspy,I am into strong tall girls. I just think of t...,2020-09-28/2020-10-04
8425,Hillary_is_Satan,That guy about halfway though the vid had a YU...,2020-09-28/2020-10-04
8426,Geralt_of_Rivia1,11.5,2020-09-28/2020-10-04
8427,Kappa,12.5,2020-09-28/2020-10-04
...,...,...,...
14912,Liberatevia300AAC,A stripper is always single if you throw enoug...,2020-11-30/2020-12-06
14913,TheImpossible1,MSM settled to avoid discovery.,2020-11-30/2020-12-06
14914,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...,2020-11-30/2020-12-06
14915,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...,2020-11-30/2020-12-06
14916,Liberatevia300AAC,In fact someone find photos of her poosi I wan...,2020-11-30/2020-12-06

In [114]:
concatenated_df = pd.concat([df1,df2], axis=0)
concatenated_df

,author,title,year_week,content
1225,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1226,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
1227,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
1228,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
1229,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
14912,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,A stripper is always single if you throw enoug...
14913,TheImpossible1,NaN,2020-11-30/2020-12-06,MSM settled to avoid discovery.
14914,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,These do not spark joy.\nAnd by joy I mean ere...
14915,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,What a stupid fucking comment she’s clearly a ...
14916,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,In fact someone find photos of her poosi I wan...

In [115]:
concatenated_df.reset_index(drop=True, inplace=True)
concatenated_df

,author,title,year_week,content
0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,2020-09-28/2020-10-04,1/7 twist. Range of projectile weights. All br...
1,salsashark,Meth took out the Christmas village way too ea...,2020-09-28/2020-10-04,NaN
2,jaylaw,I’m okay with this,2020-09-28/2020-10-04,NaN
3,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,2020-09-28/2020-10-04,NaN
4,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,2020-09-28/2020-10-04,NaN
...,...,...,...,...
7474,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,A stripper is always single if you throw enoug...
7475,TheImpossible1,NaN,2020-11-30/2020-12-06,MSM settled to avoid discovery.
7476,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,These do not spark joy.\nAnd by joy I mean ere...
7477,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,What a stupid fucking comment she’s clearly a ...
7478,Liberatevia300AAC,NaN,2020-11-30/2020-12-06,In fact someone find photos of her poosi I wan...

In [116]:
grouped = concatenated_df.groupby(['author', 'year_week']).size().reset_index(name='count')
grouped

                author              year_week  count
0     11numbereleven11  2020-11-23/2020-11-29      2
1     11numbereleven11  2020-11-30/2020-12-06      1
2            14Kaner88  2020-09-28/2020-10-04      5
3            14Kaner88  2020-10-05/2020-10-11      1
4            14Kaner88  2020-10-12/2020-10-18      2
...                ...                    ...    ...
1718             yamez  2020-11-23/2020-11-29      2
1719             yamez  2020-11-30/2020-12-06      3
1720            yitiat  2020-11-23/2020-11-29      4
1721             yoisi  2020-11-23/2020-11-29      1
1722         zeuskabob  2020-11-30/2020-12-06      4

[1723 rows x 3 columns]

In [117]:
vf=concatenated_df.groupby('author')['year_week'].nunique().reset_index(name='weeks_active')
vf

               author  weeks_active
0    11numbereleven11             2
1           14Kaner88             9
2            17760704             3
3      1776ReasonsWhy             1
4             1badcop             1
..                ...           ...
838     xxxMAGA420xxx             5
839             yamez             2
840            yitiat             1
841             yoisi             1
842         zeuskabob             1

[843 rows x 2 columns]

In [118]:
vf["author"].is_unique

True

In [119]:
d=vf["weeks_active"].value_counts().sort_index()
d

1     473
2     213
3      48
4      27
5      31
6       5
7      12
8      11
9      15
10      8
Name: weeks_active, dtype: int64

## Lexical

In [128]:
#scp new_range/data_bert/dotwin.csv u1472278@dtn05.chpc.utah.edu:/scratch/general/vast/u1472278/

In [10]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-09-28')&(df1['timestamp'] <= '2020-12-05')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
1225,weekendgunnit,HY2iJtpK,853492.0,2020-09-28 00:57:08,34.0,34.0,0.0,scruffyusp,14.5 or 10.5 5.56? What benis length is best? ...,/p/HY2iJtpK/145-or-105-556-what-benis-length/,1/7 twist. Range of projectile weights. All br...,NaN
1226,weekendgunnit,HY2jRSjY,854120.0,2020-09-28 03:25:13,63.0,63.0,0.0,salsashark,Meth took out the Christmas village way too ea...,https://media.weekendgunnit.win/post/LHtxK2bY....,NaN,https://media.weekendgunnit.win/preview/HY2jRS...
1227,gavinmcinnes,HY2jRTCX,854195.0,2020-09-28 03:46:07,8.0,9.0,1.0,jaylaw,I’m okay with this,https://media.gavinmcinnes.win/post/6SyQpTOO.jpeg,NaN,https://media.gavinmcinnes.win/preview/HY2jRTC...
1228,gavinmcinnes,HY2jSI9A,854460.0,2020-09-28 05:10:41,7.0,8.0,1.0,the_real_friend0rags,Trump Protestestors Get Emotional When Asked S...,https://youtu.be/eaj2CCBCKCY,NaN,https://media.gavinmcinnes.win/preview/HY2jSI9...
1229,gavinmcinnes,HY2jSYrc,854514.0,2020-09-28 05:34:23,6.0,7.0,1.0,the_real_friend0rags,Project Veritas - Absentee Ballot fraud,https://www.reddit.com/r/trump/comments/j13j9t...,NaN,https://media.gavinmcinnes.win/preview/HY2jSYr...
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,kotakuinaction2,11QlFksLz6,1444050.0,2020-12-04 22:30:19,14.0,14.0,0.0,Phreedom,Merry Wokemas!,https://www.youtube.com/watch?v=olUvaT5H8lk,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2206,kotakuinaction2,11QlFktRyq,1444420.0,2020-12-04 23:20:53,25.0,26.0,1.0,TheImpossible1,Never-Trump Traitor of Humanity Kelly Loeffler...,https://thedonald.win/p/11QlFjmQZU/omg-the-acc...,NaN,NaN
2207,kotakuinaction2,11QlFktSBM,1444458.0,2020-12-04 23:26:14,34.0,35.0,1.0,kratomlol,I hope she gives a speech on women empowerment...,https://media.kotakuinaction2.win/post/fzSLS8j...,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2208,kotakuinaction2,11QlFktjEP,1444559.0,2020-12-04 23:37:45,21.0,21.0,0.0,kratomlol,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,https://www.youtube.com/watch?v=uObXocysVA0,NaN,https://media.kotakuinaction2.win/preview/11Ql...
2209,kotakuinaction2,11QlFku0Pa,1444672.0,2020-12-04 23:55:09,28.0,28.0,0.0,AntonioOfVenice,Haroon Siddique (Guardian) engages in astonish...,https://i.imgur.com/6b0jW5o.png,NaN,https://media.kotakuinaction2.win/preview/11Ql...

In [121]:
df1=df1[["title","content","author","site"]]
df1

,title,content,author,site
1225,14.5 or 10.5 5.56? What benis length is best? ...,1/7 twist. Range of projectile weights. All br...,scruffyusp,weekendgunnit
1226,Meth took out the Christmas village way too ea...,NaN,salsashark,weekendgunnit
1227,I’m okay with this,NaN,jaylaw,gavinmcinnes
1228,Trump Protestestors Get Emotional When Asked S...,NaN,the_real_friend0rags,gavinmcinnes
1229,Project Veritas - Absentee Ballot fraud,NaN,the_real_friend0rags,gavinmcinnes
...,...,...,...,...
2205,Merry Wokemas!,NaN,Phreedom,kotakuinaction2
2206,Never-Trump Traitor of Humanity Kelly Loeffler...,NaN,TheImpossible1,kotakuinaction2
2207,I hope she gives a speech on women empowerment...,NaN,kratomlol,kotakuinaction2
2208,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,NaN,kratomlol,kotakuinaction2
2209,Haroon Siddique (Guardian) engages in astonish...,NaN,AntonioOfVenice,kotakuinaction2

In [124]:
df1.to_csv("../largedata/new_range/data_bert/posts_range.csv",index=False)

In [122]:
file_path="../largedata/dotwin/dotwin_comments.pkl"
df2=pd.read_pickle(file_path)
df2["timestamp"]=pd.to_datetime(df2["timestamp"])
df2= df2[(df2['timestamp'] >= '2020-09-28')&(df2['timestamp'] <= '2020-12-05')]
df2

,site,pid,permalink,timestamp,upvotes,downvotes,author,content
8423,weekendgunnit,HY2hCs5O,/p/HY2hCs5O/x/c/17s5kGvXzn,2020-09-28 00:01:04,5,0,scruffyusp,I'm down so long as automatics are cool too.\n...
8424,gavinmcinnes,HY2g3esr,/p/HY2g3esr/x/c/17s5kI3fXA,2020-09-28 00:28:29,2,0,julyspy,I am into strong tall girls. I just think of t...
8425,gavinmcinnes,HY2hAwsL,/p/HY2hAwsL/x/c/17s5kJC3aX,2020-09-28 00:54:18,4,0,Hillary_is_Satan,That guy about halfway though the vid had a YU...
8426,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCKyA,2020-09-28 00:59:08,6,1,Geralt_of_Rivia1,11.5
8427,weekendgunnit,HY2iJtpK,/p/HY2iJtpK/x/c/17s5kJCLEl,2020-09-28 01:00:19,7,0,Kappa,12.5
...,...,...,...,...,...,...,...,...
14912,weekendgunnit,11QS7j6vy9,/p/11QS7j6vy9/x/c/4DpMxaz4th2,2020-12-04 23:54:19,1,0,Liberatevia300AAC,A stripper is always single if you throw enoug...
14913,kotakuinaction2,11QlFhTiFy,/p/11QlFhTiFy/x/c/4DpMxaz4u1h,2020-12-04 23:54:59,4,0,TheImpossible1,MSM settled to avoid discovery.
14914,weekendgunnit,11QlB9tujt,/p/11QlB9tujt/x/c/4DpMxaz5B0S,2020-12-04 23:55:55,5,0,Liberatevia300AAC,These do not spark joy.\nAnd by joy I mean ere...
14915,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BMw7,2020-12-04 23:58:08,4,0,Liberatevia300AAC,What a stupid fucking comment she’s clearly a ...
14916,weekendgunnit,11QlFibYoT,/p/11QlFibYoT/x/c/4DpMxb0BNCb,2020-12-04 23:58:36,4,0,Liberatevia300AAC,In fact someone find photos of her poosi I wan...

In [123]:
df2=df2[["content","author","site"]]
df2

,content,author,site
8423,I'm down so long as automatics are cool too.\n...,scruffyusp,weekendgunnit
8424,I am into strong tall girls. I just think of t...,julyspy,gavinmcinnes
8425,That guy about halfway though the vid had a YU...,Hillary_is_Satan,gavinmcinnes
8426,11.5,Geralt_of_Rivia1,weekendgunnit
8427,12.5,Kappa,weekendgunnit
...,...,...,...
14912,A stripper is always single if you throw enoug...,Liberatevia300AAC,weekendgunnit
14913,MSM settled to avoid discovery.,TheImpossible1,kotakuinaction2
14914,These do not spark joy.\nAnd by joy I mean ere...,Liberatevia300AAC,weekendgunnit
14915,What a stupid fucking comment she’s clearly a ...,Liberatevia300AAC,weekendgunnit
14916,In fact someone find photos of her poosi I wan...,Liberatevia300AAC,weekendgunnit

In [125]:
df2.to_csv("../largedata/new_range/data_bert/comments_range.csv",index=False)

In [126]:
cc=pd.read_csv("../largedata/new_range/data_bert/posts_range.csv")
cc

,title,content,author,site
0,14.5 or 10.5 5.56? What benis length is best? ...,1/7 twist. Range of projectile weights. All br...,scruffyusp,weekendgunnit
1,Meth took out the Christmas village way too ea...,NaN,salsashark,weekendgunnit
2,I’m okay with this,NaN,jaylaw,gavinmcinnes
3,Trump Protestestors Get Emotional When Asked S...,NaN,the_real_friend0rags,gavinmcinnes
4,Project Veritas - Absentee Ballot fraud,NaN,the_real_friend0rags,gavinmcinnes
...,...,...,...,...
980,Merry Wokemas!,NaN,Phreedom,kotakuinaction2
981,Never-Trump Traitor of Humanity Kelly Loeffler...,NaN,TheImpossible1,kotakuinaction2
982,I hope she gives a speech on women empowerment...,NaN,kratomlol,kotakuinaction2
983,#CNNRAW 9-8-20 from Project Veritas. 54 minute...,NaN,kratomlol,kotakuinaction2
984,Haroon Siddique (Guardian) engages in astonish...,NaN,AntonioOfVenice,kotakuinaction2

In [127]:
bb=pd.read_csv("../largedata/new_range/data_bert/comments_range.csv")
bb

,content,author,site
0,I'm down so long as automatics are cool too.\n...,scruffyusp,weekendgunnit
1,I am into strong tall girls. I just think of t...,julyspy,gavinmcinnes
2,That guy about halfway though the vid had a YU...,Hillary_is_Satan,gavinmcinnes
3,11.5,Geralt_of_Rivia1,weekendgunnit
4,12.5,Kappa,weekendgunnit
...,...,...,...
6489,A stripper is always single if you throw enoug...,Liberatevia300AAC,weekendgunnit
6490,MSM settled to avoid discovery.,TheImpossible1,kotakuinaction2
6491,These do not spark joy.\nAnd by joy I mean ere...,Liberatevia300AAC,weekendgunnit
6492,What a stupid fucking comment she’s clearly a ...,Liberatevia300AAC,weekendgunnit
6493,In fact someone find photos of her poosi I wan...,Liberatevia300AAC,weekendgunnit

# Parler

## Posts

In [1]:
import pandas as pd
import dask.dataframe as dd

# Directory containing the Parquet files
directory = "../largedata/parler/posts/"
file_paths = [directory + f'p{i}.parquet' for i in range(92)]  # Adjust the range as necessary

# Specify the columns you want to read
columns_to_load = ['creator', 'id', 'datatype', 'createdAtformatted']

# Use Dask to read only the selected columns from the Parquet files
ddf = dd.read_parquet(file_paths, columns=columns_to_load)

# Filter by 'datatype' and 'createdAtformatted'
filtered_ddf = ddf[(ddf['datatype'] == 'posts') & (ddf['createdAtformatted'] >= '2020-09-28')& (ddf['createdAtformatted'] <= '2020-12-05')]

# Group by 'creator' and count the occurrences
grouped_data = filtered_ddf.groupby('creator').count().compute()
grouped_data
# Save the result to a CSV file
# grouped_data.to_csv('posts_filtered_from_august.csv', index=True)

# Optionally, print the first few rows to verify
print(grouped_data.head())

IOStream.flush timed out
IOStream.flush timed out

                                   id  datatype  createdAtformatted
creator
00006c1afa044f8f9037f9eb284fb411   47        47                  47
00008f04f36948028f28adc15ce6010f  133       133                 133
0000b89060c84960b164b6aa73ad3bfe   53        53                  53
0000cddfab414a61b88a84510b64d523    6         6                   6
00012ae1e36f4bab92575c3c199d999d    1         1                   1

In [2]:
grouped_data

                                   id  datatype  createdAtformatted
creator
00006c1afa044f8f9037f9eb284fb411   47        47                  47
00008f04f36948028f28adc15ce6010f  133       133                 133
0000b89060c84960b164b6aa73ad3bfe   53        53                  53
0000cddfab414a61b88a84510b64d523    6         6                   6
00012ae1e36f4bab92575c3c199d999d    1         1                   1
...                               ...       ...                 ...
ffc152ef05d345d6b697a4c28706bf98    1         1                   1
ffd2df879d504743819916c52c7a3acb    1         1                   1
ffeaa5c71fd64c5db52448d2bbf2fa54    1         1                   1
ffebef97c9e6485b94ed8f380a10b17f    1         1                   1
fff4ecbcd2b54826af0c5921ecf09d94    1         1                   1

[1774518 rows x 3 columns]

In [3]:
grouped_data=grouped_data.reset_index()
grouped_data

                                  creator   id  datatype  createdAtformatted
0        00006c1afa044f8f9037f9eb284fb411   47        47                  47
1        00008f04f36948028f28adc15ce6010f  133       133                 133
2        0000b89060c84960b164b6aa73ad3bfe   53        53                  53
3        0000cddfab414a61b88a84510b64d523    6         6                   6
4        00012ae1e36f4bab92575c3c199d999d    1         1                   1
...                                   ...  ...       ...                 ...
1774513  ffc152ef05d345d6b697a4c28706bf98    1         1                   1
1774514  ffd2df879d504743819916c52c7a3acb    1         1                   1
1774515  ffeaa5c71fd64c5db52448d2bbf2fa54    1         1                   1
1774516  ffebef97c9e6485b94ed8f380a10b17f    1         1                   1
1774517  fff4ecbcd2b54826af0c5921ecf09d94    1         1                   1

[1774518 rows x 4 columns]

In [4]:
grouped_data["creator"].is_unique

True

In [5]:
grouped_data=grouped_data.drop(columns=["datatype","createdAtformatted"])
grouped_data

                                  creator   id
0        00006c1afa044f8f9037f9eb284fb411   47
1        00008f04f36948028f28adc15ce6010f  133
2        0000b89060c84960b164b6aa73ad3bfe   53
3        0000cddfab414a61b88a84510b64d523    6
4        00012ae1e36f4bab92575c3c199d999d    1
...                                   ...  ...
1774513  ffc152ef05d345d6b697a4c28706bf98    1
1774514  ffd2df879d504743819916c52c7a3acb    1
1774515  ffeaa5c71fd64c5db52448d2bbf2fa54    1
1774516  ffebef97c9e6485b94ed8f380a10b17f    1
1774517  fff4ecbcd2b54826af0c5921ecf09d94    1

[1774518 rows x 2 columns]

In [6]:
grouped_data=grouped_data.rename(columns={"id":"#posts"})
grouped_data

                                  creator  #posts
0        00006c1afa044f8f9037f9eb284fb411      47
1        00008f04f36948028f28adc15ce6010f     133
2        0000b89060c84960b164b6aa73ad3bfe      53
3        0000cddfab414a61b88a84510b64d523       6
4        00012ae1e36f4bab92575c3c199d999d       1
...                                   ...     ...
1774513  ffc152ef05d345d6b697a4c28706bf98       1
1774514  ffd2df879d504743819916c52c7a3acb       1
1774515  ffeaa5c71fd64c5db52448d2bbf2fa54       1
1774516  ffebef97c9e6485b94ed8f380a10b17f       1
1774517  fff4ecbcd2b54826af0c5921ecf09d94       1

[1774518 rows x 2 columns]

In [7]:
grouped_data.to_csv("../largedata/new_range/same_range/parler_posts.csv",index=False)

- We can see that the loss of rows is not a lot as this range covers the peak of Parler, the election time.

## Comments

In [1]:
import dask.dataframe as dd

# Directory containing the Parquet files
directory = "../largedata/parler/posts/"
file_paths = [directory + f'p{i}.parquet' for i in range(92)]  # Adjust the range as necessary

# Specify the columns you want to read
columns_to_load = ['creator', 'id','datatype','post','createdAtformatted']



# Use Dask to read only the selected columns from the Parquet files
ddf = dd.read_parquet(file_paths, columns=columns_to_load)
filtered_ddf = ddf[(ddf['datatype'] == 'comments') & (ddf['createdAtformatted'] >= '2020-08-01')& (ddf['createdAtformatted'] <= '2020-12-05')]

# Print the first few rows to verify the data
grouped_data_1 = filtered_ddf.groupby('post').count().compute() 
grouped_data_1
# grouped_data.to_csv('comments1.csv', index=True)

                                  creator   id  datatype  createdAtformatted
post
000002e75c65473099279dff7124b4a7        2    2         2                   2
000011114f5c4a9a99a6317f577b8cd7       10   10        10                  10
00005faafb4d4e2da1e96f6459452f38        3    3         3                   3
0000672c938548bf8f667fd412223584        5    5         5                   5
0000ee9f125d4efd838379ecf59f4f0d      652  652       652                 652
...                                   ...  ...       ...                 ...
fff8415389234b81a8a20cbd176899bd        1    1         1                   1
fffab9373a5b4b4e8ecd4b6e3375cc22        1    1         1                   1
fffacf6ea1ad49c9a097297b59cf301a        1    1         1                   1
fffc326a93b84b87a4816d5a2871acc7        1    1         1                   1
fffc8f9e941f4125a6f515596b8c54fc        1    1         1                   1

[10930759 rows x 4 columns]

In [2]:
grouped_data_1=grouped_data_1.reset_index()

In [3]:
grouped_data_1=grouped_data_1.drop(columns=["datatype","createdAtformatted","creator"])
grouped_data_1

                                      post   id
0         000002e75c65473099279dff7124b4a7    2
1         000011114f5c4a9a99a6317f577b8cd7   10
2         00005faafb4d4e2da1e96f6459452f38    3
3         0000672c938548bf8f667fd412223584    5
4         0000ee9f125d4efd838379ecf59f4f0d  652
...                                    ...  ...
10930754  fff8415389234b81a8a20cbd176899bd    1
10930755  fffab9373a5b4b4e8ecd4b6e3375cc22    1
10930756  fffacf6ea1ad49c9a097297b59cf301a    1
10930757  fffc326a93b84b87a4816d5a2871acc7    1
10930758  fffc8f9e941f4125a6f515596b8c54fc    1

[10930759 rows x 2 columns]

In [4]:
grouped_data_1=grouped_data_1.rename(columns={"id":"#comments_received"})
grouped_data_1

                                      post  #comments_received
0         000002e75c65473099279dff7124b4a7                   2
1         000011114f5c4a9a99a6317f577b8cd7                  10
2         00005faafb4d4e2da1e96f6459452f38                   3
3         0000672c938548bf8f667fd412223584                   5
4         0000ee9f125d4efd838379ecf59f4f0d                 652
...                                    ...                 ...
10930754  fff8415389234b81a8a20cbd176899bd                   1
10930755  fffab9373a5b4b4e8ecd4b6e3375cc22                   1
10930756  fffacf6ea1ad49c9a097297b59cf301a                   1
10930757  fffc326a93b84b87a4816d5a2871acc7                   1
10930758  fffc8f9e941f4125a6f515596b8c54fc                   1

[10930759 rows x 2 columns]

In [5]:
grouped_data_1["post"].is_unique

True

In [6]:
grouped_data_1.to_csv("../largedata/new_range/same_range/parler_posts_comments_received.csv",index=False)

In [8]:
import dask.dataframe as dd

# Directory containing the Parquet files
directory = "../largedata/parler/posts/"
file_paths = [directory + f'p{i}.parquet' for i in range(0,92)]  # Adjust the range as necessary

# Specify the columns you want to read
columns_to_load = ['creator', 'id','datatype','createdAtformatted']



# Use Dask to read only the selected columns from the Parquet files
ddf = dd.read_parquet(file_paths, columns=columns_to_load)
filtered_ddf = ddf[(ddf['datatype'] == 'posts') & (ddf['createdAtformatted'] >= '2020-08-01')&(ddf['createdAtformatted'] <= '2020-12-05')]

# Print the first few rows to verify the data
grouped_data_3 = filtered_ddf.compute() 
grouped_data_3
#grouped_data.to_csv('comments2.csv', index=True)

,creator,id,datatype,createdAtformatted
1,436362cdd252424a994e6eded06183cd,6f23e4b3e12f45bf91736e3e0e992ce1,posts,2020-11-23 11:46:20 UTC
2,f34f55277e02489baffc0ac0a9a0a556,ceb74aa6aa6244ecb34f9c7b61f555f0,posts,2020-11-02 12:51:01 UTC
5,653ba961088c4d1f8997599fe19c9b64,e5afe213e01f4429a865f4aba9a97172,posts,2020-10-26 02:41:50 UTC
14,325b0d9b2cc54c92bc314be7b3571806,af2f83442c2d48eb9cc79486dbb8f2da,posts,2020-11-21 13:44:08 UTC
17,f256a63a8e97473ba0dd7eba8d7704a6,cb737b105cab40848963d79c33f47e3a,posts,2020-09-14 03:31:30 UTC
...,...,...,...,...
1063291,11caffddf11b4439aa2b5a412f93f1f4,32feffc908e945f399b3934a841a61ab,posts,2020-10-26 06:57:10 UTC
1063292,099ba62eabc440349a2b116b71414937,b168bdfb991a49d98ad8cf1c97aa495e,posts,2020-10-14 00:07:03 UTC
1063295,68694fd1c9a64212879b11dbdd7fdcd2,51f99f0ee9fa47c89cb4b75c0316c94a,posts,2020-09-01 22:24:03 UTC
1063298,647c271c20e54d9c98d8c81930038b60,e2b1db8300f04d039ff76e6c32883345,posts,2020-08-28 13:52:56 UTC
1063301,c6a7240c441d48e8b45cf6e2b095b13e,44ab9f537a644fb384abd1718496dab1,posts,2020-11-03 02:42:47 UTC

In [9]:
grouped_data_3=grouped_data_3.drop(columns=["datatype","createdAtformatted"])
grouped_data_3

                                  creator                                id
1        436362cdd252424a994e6eded06183cd  6f23e4b3e12f45bf91736e3e0e992ce1
2        f34f55277e02489baffc0ac0a9a0a556  ceb74aa6aa6244ecb34f9c7b61f555f0
5        653ba961088c4d1f8997599fe19c9b64  e5afe213e01f4429a865f4aba9a97172
14       325b0d9b2cc54c92bc314be7b3571806  af2f83442c2d48eb9cc79486dbb8f2da
17       f256a63a8e97473ba0dd7eba8d7704a6  cb737b105cab40848963d79c33f47e3a
...                                   ...                               ...
1063291  11caffddf11b4439aa2b5a412f93f1f4  32feffc908e945f399b3934a841a61ab
1063292  099ba62eabc440349a2b116b71414937  b168bdfb991a49d98ad8cf1c97aa495e
1063295  68694fd1c9a64212879b11dbdd7fdcd2  51f99f0ee9fa47c89cb4b75c0316c94a
1063298  647c271c20e54d9c98d8c81930038b60  e2b1db8300f04d039ff76e6c32883345
1063301  c6a7240c441d48e8b45cf6e2b095b13e  44ab9f537a644fb384abd1718496dab1

[52386280 rows x 2 columns]

In [10]:
grouped_data_3=grouped_data_3.rename(columns={"id":"post"})
grouped_data_3

                                  creator                              post
1        436362cdd252424a994e6eded06183cd  6f23e4b3e12f45bf91736e3e0e992ce1
2        f34f55277e02489baffc0ac0a9a0a556  ceb74aa6aa6244ecb34f9c7b61f555f0
5        653ba961088c4d1f8997599fe19c9b64  e5afe213e01f4429a865f4aba9a97172
14       325b0d9b2cc54c92bc314be7b3571806  af2f83442c2d48eb9cc79486dbb8f2da
17       f256a63a8e97473ba0dd7eba8d7704a6  cb737b105cab40848963d79c33f47e3a
...                                   ...                               ...
1063291  11caffddf11b4439aa2b5a412f93f1f4  32feffc908e945f399b3934a841a61ab
1063292  099ba62eabc440349a2b116b71414937  b168bdfb991a49d98ad8cf1c97aa495e
1063295  68694fd1c9a64212879b11dbdd7fdcd2  51f99f0ee9fa47c89cb4b75c0316c94a
1063298  647c271c20e54d9c98d8c81930038b60  e2b1db8300f04d039ff76e6c32883345
1063301  c6a7240c441d48e8b45cf6e2b095b13e  44ab9f537a644fb384abd1718496dab1

[52386280 rows x 2 columns]

In [11]:
grouped_data_3.to_csv("../largedata/new_range/same_range/parler_posts_creator.csv",index=False)

In [13]:
print("hello")

hello

In [1]:
import pandas as pd
grouped_data_1=pd.read_csv("../largedata/new_range/same_range/parler_posts_comments_received.csv")

In [2]:
grouped_data_1

                                      post  #comments_received
0         000002e75c65473099279dff7124b4a7                   2
1         000011114f5c4a9a99a6317f577b8cd7                  10
2         00005faafb4d4e2da1e96f6459452f38                   3
3         0000672c938548bf8f667fd412223584                   5
4         0000ee9f125d4efd838379ecf59f4f0d                 652
...                                    ...                 ...
10930754  fff8415389234b81a8a20cbd176899bd                   1
10930755  fffab9373a5b4b4e8ecd4b6e3375cc22                   1
10930756  fffacf6ea1ad49c9a097297b59cf301a                   1
10930757  fffc326a93b84b87a4816d5a2871acc7                   1
10930758  fffc8f9e941f4125a6f515596b8c54fc                   1

[10930759 rows x 2 columns]

In [3]:
grouped_data_3=pd.read_csv("../largedata/new_range/same_range/parler_posts_creator.csv")
grouped_data_3

                                   creator                              post
0         436362cdd252424a994e6eded06183cd  6f23e4b3e12f45bf91736e3e0e992ce1
1         f34f55277e02489baffc0ac0a9a0a556  ceb74aa6aa6244ecb34f9c7b61f555f0
2         653ba961088c4d1f8997599fe19c9b64  e5afe213e01f4429a865f4aba9a97172
3         325b0d9b2cc54c92bc314be7b3571806  af2f83442c2d48eb9cc79486dbb8f2da
4         f256a63a8e97473ba0dd7eba8d7704a6  cb737b105cab40848963d79c33f47e3a
...                                    ...                               ...
52386275  11caffddf11b4439aa2b5a412f93f1f4  32feffc908e945f399b3934a841a61ab
52386276  099ba62eabc440349a2b116b71414937  b168bdfb991a49d98ad8cf1c97aa495e
52386277  68694fd1c9a64212879b11dbdd7fdcd2  51f99f0ee9fa47c89cb4b75c0316c94a
52386278  647c271c20e54d9c98d8c81930038b60  e2b1db8300f04d039ff76e6c32883345
52386279  c6a7240c441d48e8b45cf6e2b095b13e  44ab9f537a644fb384abd1718496dab1

[52386280 rows x 2 columns]

In [4]:
combined_df = pd.merge(grouped_data_3, grouped_data_1, on='post', how='inner')
combined_df

,creator,post,#comments_received
0,acd3930a06e240818390f15bac661629,9ec63bbaaaeb49999fba98c57c9776c1,1
1,2992c35529244dbe9b36353035562ecc,03a33555c0f647c594d3703576d9be67,5
2,979d4ea34bae4e54abcb7554ad8be346,bf30724c60774ae49266718f5e3cfd96,2
3,d9c8f68fb6f04f9fbe5fb171ca937892,00dfffab0eaa40aa93f0e2ea449f01f1,1
4,979d4ea34bae4e54abcb7554ad8be346,46988aa3192e45ab9f4f92814e4d5941,2
...,...,...,...
3062253,9209855ff534112344b7bc925c90eb53,4aacd55d2138410f891e72efed8e328f,1
3062254,5e15d71f0ef849dfbb4b88e4b8ae33f3,517df582e91d44d094774be801a860a3,1
3062255,1bfd30df9ea74293b11264fcfd7b14e5,0b21edd1a60a44678b1ef52ea4eb92d7,1
3062256,ca7cce78bd8b4f8da7a5a4e892da8976,ae5f39e202fb404291b3187be6fca644,1
3062257,647c271c20e54d9c98d8c81930038b60,e2b1db8300f04d039ff76e6c32883345,1

In [5]:
combined_df["creator"].nunique()

1161905

In [6]:
a=combined_df.groupby('creator')['#comments_received'].sum().reset_index()
a

                                  creator  #comments_received
0        0000064f36da4e6a90deb74b7003baac                   2
1        00001e14d76240af8574c98c3e8a3753                   2
2        000021d3cb1e4b1bb5e0a9823497f993                   4
3        0000419ead224413927479d97961b19e                   2
4        00005fbccc9043a2a3c2965a11b024a3                   1
...                                   ...                 ...
1161900  ffffb7d7619b4f118e65dc12f80e2842                   2
1161901  ffffb7eb36cd4a1080e4bef9e8b2295a                   1
1161902  ffffcf047dae4910ac9c786e54f2074d                   2
1161903  fffff1a4016c49ce90f921ddfa19a3bd                   1
1161904  fffffb0fa5ad478a8035c806bf8ca24f                   2

[1161905 rows x 2 columns]

In [7]:
a["creator"].is_unique

True

In [8]:
g=pd.read_csv("../largedata/new_range/same_range/parler_posts.csv")
g

                                  creator  #posts
0        00006c1afa044f8f9037f9eb284fb411      47
1        00008f04f36948028f28adc15ce6010f     133
2        0000b89060c84960b164b6aa73ad3bfe      53
3        0000cddfab414a61b88a84510b64d523       6
4        00012ae1e36f4bab92575c3c199d999d       1
...                                   ...     ...
1774513  ffc152ef05d345d6b697a4c28706bf98       1
1774514  ffd2df879d504743819916c52c7a3acb       1
1774515  ffeaa5c71fd64c5db52448d2bbf2fa54       1
1774516  ffebef97c9e6485b94ed8f380a10b17f       1
1774517  fff4ecbcd2b54826af0c5921ecf09d94       1

[1774518 rows x 2 columns]

In [9]:
g["creator"].is_unique

True

In [10]:
g

                                  creator  #posts
0        00006c1afa044f8f9037f9eb284fb411      47
1        00008f04f36948028f28adc15ce6010f     133
2        0000b89060c84960b164b6aa73ad3bfe      53
3        0000cddfab414a61b88a84510b64d523       6
4        00012ae1e36f4bab92575c3c199d999d       1
...                                   ...     ...
1774513  ffc152ef05d345d6b697a4c28706bf98       1
1774514  ffd2df879d504743819916c52c7a3acb       1
1774515  ffeaa5c71fd64c5db52448d2bbf2fa54       1
1774516  ffebef97c9e6485b94ed8f380a10b17f       1
1774517  fff4ecbcd2b54826af0c5921ecf09d94       1

[1774518 rows x 2 columns]

In [11]:
a

                                  creator  #comments_received
0        0000064f36da4e6a90deb74b7003baac                   2
1        00001e14d76240af8574c98c3e8a3753                   2
2        000021d3cb1e4b1bb5e0a9823497f993                   4
3        0000419ead224413927479d97961b19e                   2
4        00005fbccc9043a2a3c2965a11b024a3                   1
...                                   ...                 ...
1161900  ffffb7d7619b4f118e65dc12f80e2842                   2
1161901  ffffb7eb36cd4a1080e4bef9e8b2295a                   1
1161902  ffffcf047dae4910ac9c786e54f2074d                   2
1161903  fffff1a4016c49ce90f921ddfa19a3bd                   1
1161904  fffffb0fa5ad478a8035c806bf8ca24f                   2

[1161905 rows x 2 columns]

In [12]:
foo=pd.merge(a, g, on='creator', how='outer')
foo

                                  creator  #comments_received  #posts
0        0000064f36da4e6a90deb74b7003baac                 2.0     1.0
1        00001e14d76240af8574c98c3e8a3753                 2.0     1.0
2        000021d3cb1e4b1bb5e0a9823497f993                 4.0     1.0
3        0000419ead224413927479d97961b19e                 2.0     1.0
4        00005fbccc9043a2a3c2965a11b024a3                 1.0     1.0
...                                   ...                 ...     ...
1818775  ffb018c89cee41bebb1066c90d05237f                 NaN     1.0
1818776  ffb0ac6782b747f59d03555e64f04daa                 NaN     1.0
1818777  ffb877b58c8d4bf9a246b521adda0505                 NaN     1.0
1818778  ffeaa5c71fd64c5db52448d2bbf2fa54                 NaN     1.0
1818779  fff4ecbcd2b54826af0c5921ecf09d94                 NaN     1.0

[1818780 rows x 3 columns]

In [13]:
foo.to_csv("../largedata/new_range/same_range/parler_posts_comments_received.csv",index=False)

In [23]:
foo=pd.read_csv("../largedata/new_range/same_range/parler_posts_comments_received.csv")
foo

                                  creator  #comments_received  #posts
0        0000064f36da4e6a90deb74b7003baac                 2.0     1.0
1        00001e14d76240af8574c98c3e8a3753                 2.0     1.0
2        000021d3cb1e4b1bb5e0a9823497f993                 4.0     1.0
3        0000419ead224413927479d97961b19e                 2.0     1.0
4        00005fbccc9043a2a3c2965a11b024a3                 1.0     1.0
...                                   ...                 ...     ...
1818775  ffb018c89cee41bebb1066c90d05237f                 NaN     1.0
1818776  ffb0ac6782b747f59d03555e64f04daa                 NaN     1.0
1818777  ffb877b58c8d4bf9a246b521adda0505                 NaN     1.0
1818778  ffeaa5c71fd64c5db52448d2bbf2fa54                 NaN     1.0
1818779  fff4ecbcd2b54826af0c5921ecf09d94                 NaN     1.0

[1818780 rows x 3 columns]

In [24]:
foo[(foo["#posts"].isna()) & (~foo["#comments_received"].isna())]

                                  creator  #comments_received  #posts
45       000305a0009d432ea5f18c0a7beeba30                 1.0     NaN
48       00034dccc49f4adcaa1c6bab22364226                 1.0     NaN
124      0007c237321a417fa309bc1041badf12                 1.0     NaN
158      0009b5a1cd8b49fb8b488381fd4a9b4d                 1.0     NaN
164      000a18d5b5bd4fd4a8c00c6b4e7e01df                 1.0     NaN
...                                   ...                 ...     ...
1161792  fff9518ea7d94f55ac7fc1177a5d4dd2                 2.0     NaN
1161794  fff966a2813240e58f19b1aa696a55d0                 2.0     NaN
1161836  fffc32426dd44adfadd90c92462467e1                 4.0     NaN
1161887  ffff4da6d9214dd28ce54f618ecfa25f                 1.0     NaN
1161902  ffffcf047dae4910ac9c786e54f2074d                 2.0     NaN

[44262 rows x 3 columns]

## users

In [3]:
import dask.dataframe as dd

# Directory containing the Parquet files
#file_name = f"part-{i:05d}-880ce7f0-fc4f-4e18-8ba5-728914128104-c000.snappy.parquet"
directory = "../largedata/parler/users/"
file_paths = [directory + f"part-{i:05d}-880ce7f0-fc4f-4e18-8ba5-728914128104-c000.snappy.parquet" for i in range(35)]  # Adjust the range as necessary

# Specify the columns you want to read
columns_to_load = ['id','user_followers','user_following','joined']

# Use Dask to read only the selected columns from the Parquet files
ddf = dd.read_parquet(file_paths, columns=columns_to_load)


# Print the first few rows to verify the data
grouped = ddf.compute() 
grouped

,id,user_followers,user_following,joined
0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,2018-08-26 02:05:19
1,a078092e6e2df507bfd12db4713f2db7,33.0,13.0,2018-08-31 23:04:12
2,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,2018-08-25 23:55:50
3,a078092e6e2df507bfd12db4710da666,307.0,28.0,2018-08-28 14:14:40
4,a078092e6e2df507bfd12db471238cc0,NaN,NaN,2018-08-29 14:50:55
...,...,...,...,...
314722,6eb75d964f824b02923cab1cc2ffbcdb,0.0,9.0,2021-01-07 06:43:56
314723,66f57099e57842d2be2d2ec9ce69657f,0.0,2.0,2021-01-09 22:09:33
314724,0e2cbc5566c94beeb42e28fa7b7b8313,NaN,NaN,2021-01-05 04:25:34
314725,ba7b21dcd9004fad8881d772ea05bd14,0.0,0.0,2021-01-03 00:25:12
314726,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,2021-01-09 22:06:22

In [4]:
grouped=grouped.drop(columns=["joined"])
grouped

                                      id  user_followers  user_following
0       a078092e6e2df507bfd12db4710709ec           549.0           166.0
1       a078092e6e2df507bfd12db4713f2db7            33.0            13.0
2       a078092e6e2df507bfd12db471063dd0          1200.0           394.0
3       a078092e6e2df507bfd12db4710da666           307.0            28.0
4       a078092e6e2df507bfd12db471238cc0             NaN             NaN
...                                  ...             ...             ...
314722  6eb75d964f824b02923cab1cc2ffbcdb             0.0             9.0
314723  66f57099e57842d2be2d2ec9ce69657f             0.0             2.0
314724  0e2cbc5566c94beeb42e28fa7b7b8313             NaN             NaN
314725  ba7b21dcd9004fad8881d772ea05bd14             0.0             0.0
314726  4cee5a4de9224a13bc34af6cb4f88bfd             0.0             1.0

[13254060 rows x 3 columns]

In [5]:
grouped=grouped.reset_index(drop=True)
grouped

                                        id  user_followers  user_following
0         a078092e6e2df507bfd12db4710709ec           549.0           166.0
1         a078092e6e2df507bfd12db4713f2db7            33.0            13.0
2         a078092e6e2df507bfd12db471063dd0          1200.0           394.0
3         a078092e6e2df507bfd12db4710da666           307.0            28.0
4         a078092e6e2df507bfd12db471238cc0             NaN             NaN
...                                    ...             ...             ...
13254055  6eb75d964f824b02923cab1cc2ffbcdb             0.0             9.0
13254056  66f57099e57842d2be2d2ec9ce69657f             0.0             2.0
13254057  0e2cbc5566c94beeb42e28fa7b7b8313             NaN             NaN
13254058  ba7b21dcd9004fad8881d772ea05bd14             0.0             0.0
13254059  4cee5a4de9224a13bc34af6cb4f88bfd             0.0             1.0

[13254060 rows x 3 columns]

In [6]:
ta=grouped.rename(columns={"id":"creator"})
ta

                                   creator  user_followers  user_following
0         a078092e6e2df507bfd12db4710709ec           549.0           166.0
1         a078092e6e2df507bfd12db4713f2db7            33.0            13.0
2         a078092e6e2df507bfd12db471063dd0          1200.0           394.0
3         a078092e6e2df507bfd12db4710da666           307.0            28.0
4         a078092e6e2df507bfd12db471238cc0             NaN             NaN
...                                    ...             ...             ...
13254055  6eb75d964f824b02923cab1cc2ffbcdb             0.0             9.0
13254056  66f57099e57842d2be2d2ec9ce69657f             0.0             2.0
13254057  0e2cbc5566c94beeb42e28fa7b7b8313             NaN             NaN
13254058  ba7b21dcd9004fad8881d772ea05bd14             0.0             0.0
13254059  4cee5a4de9224a13bc34af6cb4f88bfd             0.0             1.0

[13254060 rows x 3 columns]

In [8]:
ta

                                   creator  user_followers  user_following
0         a078092e6e2df507bfd12db4710709ec           549.0           166.0
1         a078092e6e2df507bfd12db4713f2db7            33.0            13.0
2         a078092e6e2df507bfd12db471063dd0          1200.0           394.0
3         a078092e6e2df507bfd12db4710da666           307.0            28.0
4         a078092e6e2df507bfd12db471238cc0             NaN             NaN
...                                    ...             ...             ...
13254055  6eb75d964f824b02923cab1cc2ffbcdb             0.0             9.0
13254056  66f57099e57842d2be2d2ec9ce69657f             0.0             2.0
13254057  0e2cbc5566c94beeb42e28fa7b7b8313             NaN             NaN
13254058  ba7b21dcd9004fad8881d772ea05bd14             0.0             0.0
13254059  4cee5a4de9224a13bc34af6cb4f88bfd             0.0             1.0

[13254060 rows x 3 columns]

In [19]:
foo

                                  creator  #comments_received  #posts
0        0000064f36da4e6a90deb74b7003baac                 2.0     1.0
1        00001e14d76240af8574c98c3e8a3753                 2.0     1.0
2        000021d3cb1e4b1bb5e0a9823497f993                 4.0     1.0
3        0000419ead224413927479d97961b19e                 2.0     1.0
4        00005fbccc9043a2a3c2965a11b024a3                 1.0     1.0
...                                   ...                 ...     ...
1818775  ffb018c89cee41bebb1066c90d05237f                 NaN     1.0
1818776  ffb0ac6782b747f59d03555e64f04daa                 NaN     1.0
1818777  ffb877b58c8d4bf9a246b521adda0505                 NaN     1.0
1818778  ffeaa5c71fd64c5db52448d2bbf2fa54                 NaN     1.0
1818779  fff4ecbcd2b54826af0c5921ecf09d94                 NaN     1.0

[1818780 rows x 3 columns]

In [23]:
goo=pd.merge(ta, foo, on='creator', how='inner')
goo

,creator,user_followers,user_following,#comments_received,#posts
0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,9.0,42.0
1,a078092e6e2df507bfd12db4712236a5,10000.0,27.0,1.0,1.0
2,a078092e6e2df507bfd12db4710e3290,892000.0,10.0,23955.0,49.0
3,a078092e6e2df507bfd12db471029eb3,736000.0,409.0,126159.0,228.0
4,a078092e6e2df507bfd12db4710202ab,57000.0,73.0,498.0,12.0
...,...,...,...,...,...
1818775,24d361d4bc8741318c5c880387b6cd6c,3.0,6.0,NaN,1.0
1818776,07aecb598eac4fe49b65c074802d3d19,1.0,10.0,NaN,1.0
1818777,2cb8443f3ee944d996b5f5b96b88800f,1.0,3.0,NaN,1.0
1818778,069e4f3b777f4d0da6f61af33c979a00,0.0,2.0,NaN,1.0
1818779,be5e4c2b5e5d4b02be663c2f1b5778af,4.0,6.0,NaN,2.0

In [21]:
goo.to_csv("../largedata/new_range/same_range/parler_users_followers_following_posts_comments_received.csv",index=False)

- Inner join as we want people who posted in our time frame

## comments made

In [1]:
import pandas as pd
import dask.dataframe as dd

# Directory containing the Parquet files
directory = "../largedata/parler/posts/"
file_paths = [directory + f'p{i}.parquet' for i in range(92)]  # Adjust the range as necessary

# Specify the columns you want to read
columns_to_load = ['creator', 'id', 'datatype', 'createdAtformatted']

# Use Dask to read only the selected columns from the Parquet files
ddf = dd.read_parquet(file_paths, columns=columns_to_load)

# Filter by 'datatype' and 'createdAtformatted'
filtered_ddf = ddf[(ddf['datatype'] == 'comments') & (ddf['createdAtformatted'] >= '2020-08-01')&(ddf['createdAtformatted'] <= '2020-12-05')]

# Group by 'creator' and count the occurrences
grouped_data_5 = filtered_ddf.groupby('creator').count().compute()
grouped_data_5
# Save the result to a CSV file
# grouped_data.to_csv('posts_filtered_from_august.csv', index=True)

# Optionally, print the first few rows to verify

                                   id  datatype  createdAtformatted
creator
00012da44ef74e7ca5b77d17edbf8180   72        72                  72
00012fc9ff674c2db03131a4df15d973  120       120                 120
0001741c3596495c834983253dcb2254   27        27                  27
0001ac250d644f828f5520839d371b8b    1         1                   1
0002b9bcd61d4d73ba1f8a58d6cdb953   14        14                  14
...                               ...       ...                 ...
ff9eb2a52e7d4b1f8a007c29ba3f11d5    1         1                   1
ffa3e3c8314e47559a64767f9f2142de    1         1                   1
ffa768fd3ce84dc4807bb31e1b2bde62    1         1                   1
ffe1f14621a046669a7788cee19520cb    1         1                   1
ffebb3b9cf7a459395ec55a7ee261adb    1         1                   1

[1865149 rows x 3 columns]

In [4]:
grouped_data_5=grouped_data_5.reset_index()
grouped_data_5

                                  creator   id  datatype  createdAtformatted
0        00012da44ef74e7ca5b77d17edbf8180   72        72                  72
1        00012fc9ff674c2db03131a4df15d973  120       120                 120
2        0001741c3596495c834983253dcb2254   27        27                  27
3        0001ac250d644f828f5520839d371b8b    1         1                   1
4        0002b9bcd61d4d73ba1f8a58d6cdb953   14        14                  14
...                                   ...  ...       ...                 ...
1865144  ff9eb2a52e7d4b1f8a007c29ba3f11d5    1         1                   1
1865145  ffa3e3c8314e47559a64767f9f2142de    1         1                   1
1865146  ffa768fd3ce84dc4807bb31e1b2bde62    1         1                   1
1865147  ffe1f14621a046669a7788cee19520cb    1         1                   1
1865148  ffebb3b9cf7a459395ec55a7ee261adb    1         1                   1

[1865149 rows x 4 columns]

In [5]:
grouped_data_5=grouped_data_5.drop(columns=["datatype","createdAtformatted"])
grouped_data_5

                                  creator   id
0        00012da44ef74e7ca5b77d17edbf8180   72
1        00012fc9ff674c2db03131a4df15d973  120
2        0001741c3596495c834983253dcb2254   27
3        0001ac250d644f828f5520839d371b8b    1
4        0002b9bcd61d4d73ba1f8a58d6cdb953   14
...                                   ...  ...
1865144  ff9eb2a52e7d4b1f8a007c29ba3f11d5    1
1865145  ffa3e3c8314e47559a64767f9f2142de    1
1865146  ffa768fd3ce84dc4807bb31e1b2bde62    1
1865147  ffe1f14621a046669a7788cee19520cb    1
1865148  ffebb3b9cf7a459395ec55a7ee261adb    1

[1865149 rows x 2 columns]

In [6]:
grouped_data_5=grouped_data_5.rename(columns={"id":"#comments_made"})
grouped_data_5

                                  creator  #comments_made
0        00012da44ef74e7ca5b77d17edbf8180              72
1        00012fc9ff674c2db03131a4df15d973             120
2        0001741c3596495c834983253dcb2254              27
3        0001ac250d644f828f5520839d371b8b               1
4        0002b9bcd61d4d73ba1f8a58d6cdb953              14
...                                   ...             ...
1865144  ff9eb2a52e7d4b1f8a007c29ba3f11d5               1
1865145  ffa3e3c8314e47559a64767f9f2142de               1
1865146  ffa768fd3ce84dc4807bb31e1b2bde62               1
1865147  ffe1f14621a046669a7788cee19520cb               1
1865148  ffebb3b9cf7a459395ec55a7ee261adb               1

[1865149 rows x 2 columns]

In [3]:
foo=pd.read_csv("../largedata/new_range/same_range/parler_posts_comments_received.csv")
foo

                                  creator  #comments_received  #posts
0        0000064f36da4e6a90deb74b7003baac                 2.0     1.0
1        00001e14d76240af8574c98c3e8a3753                 2.0     1.0
2        000021d3cb1e4b1bb5e0a9823497f993                 4.0     1.0
3        0000419ead224413927479d97961b19e                 2.0     1.0
4        00005fbccc9043a2a3c2965a11b024a3                 1.0     1.0
...                                   ...                 ...     ...
1818775  ffb018c89cee41bebb1066c90d05237f                 NaN     1.0
1818776  ffb0ac6782b747f59d03555e64f04daa                 NaN     1.0
1818777  ffb877b58c8d4bf9a246b521adda0505                 NaN     1.0
1818778  ffeaa5c71fd64c5db52448d2bbf2fa54                 NaN     1.0
1818779  fff4ecbcd2b54826af0c5921ecf09d94                 NaN     1.0

[1818780 rows x 3 columns]

In [7]:
loo=pd.merge(grouped_data_5, foo, on='creator', how='outer')
loo

,creator,#comments_made,#comments_received,#posts
0,00012da44ef74e7ca5b77d17edbf8180,72.0,NaN,NaN
1,00012fc9ff674c2db03131a4df15d973,120.0,NaN,NaN
2,0001741c3596495c834983253dcb2254,27.0,NaN,NaN
3,0001ac250d644f828f5520839d371b8b,1.0,NaN,NaN
4,0002b9bcd61d4d73ba1f8a58d6cdb953,14.0,NaN,NaN
...,...,...,...,...
3146541,ffb018c89cee41bebb1066c90d05237f,NaN,NaN,1.0
3146542,ffb0ac6782b747f59d03555e64f04daa,NaN,NaN,1.0
3146543,ffb877b58c8d4bf9a246b521adda0505,NaN,NaN,1.0
3146544,ffeaa5c71fd64c5db52448d2bbf2fa54,NaN,NaN,1.0
3146545,fff4ecbcd2b54826af0c5921ecf09d94,NaN,NaN,1.0

In [8]:
loo.to_csv("../largedata/new_range/same_range/parler_posts_comments_received_comments_made.csv",index=False)

## Final Merge

In [9]:
loo

,creator,#comments_made,#comments_received,#posts
0,00012da44ef74e7ca5b77d17edbf8180,72.0,NaN,NaN
1,00012fc9ff674c2db03131a4df15d973,120.0,NaN,NaN
2,0001741c3596495c834983253dcb2254,27.0,NaN,NaN
3,0001ac250d644f828f5520839d371b8b,1.0,NaN,NaN
4,0002b9bcd61d4d73ba1f8a58d6cdb953,14.0,NaN,NaN
...,...,...,...,...
3146541,ffb018c89cee41bebb1066c90d05237f,NaN,NaN,1.0
3146542,ffb0ac6782b747f59d03555e64f04daa,NaN,NaN,1.0
3146543,ffb877b58c8d4bf9a246b521adda0505,NaN,NaN,1.0
3146544,ffeaa5c71fd64c5db52448d2bbf2fa54,NaN,NaN,1.0
3146545,fff4ecbcd2b54826af0c5921ecf09d94,NaN,NaN,1.0

In [2]:
import pandas as pd
loo=pd.read_csv("../largedata/new_range/same_range/parler_posts_comments_received_comments_made.csv")
loo

,creator,#comments_made,#comments_received,#posts
0,00012da44ef74e7ca5b77d17edbf8180,72.0,NaN,NaN
1,00012fc9ff674c2db03131a4df15d973,120.0,NaN,NaN
2,0001741c3596495c834983253dcb2254,27.0,NaN,NaN
3,0001ac250d644f828f5520839d371b8b,1.0,NaN,NaN
4,0002b9bcd61d4d73ba1f8a58d6cdb953,14.0,NaN,NaN
...,...,...,...,...
3146541,ffb018c89cee41bebb1066c90d05237f,NaN,NaN,1.0
3146542,ffb0ac6782b747f59d03555e64f04daa,NaN,NaN,1.0
3146543,ffb877b58c8d4bf9a246b521adda0505,NaN,NaN,1.0
3146544,ffeaa5c71fd64c5db52448d2bbf2fa54,NaN,NaN,1.0
3146545,fff4ecbcd2b54826af0c5921ecf09d94,NaN,NaN,1.0

In [9]:
ta

                                   creator  user_followers  user_following
0         a078092e6e2df507bfd12db4710709ec           549.0           166.0
1         a078092e6e2df507bfd12db4713f2db7            33.0            13.0
2         a078092e6e2df507bfd12db471063dd0          1200.0           394.0
3         a078092e6e2df507bfd12db4710da666           307.0            28.0
4         a078092e6e2df507bfd12db471238cc0             NaN             NaN
...                                    ...             ...             ...
13254055  6eb75d964f824b02923cab1cc2ffbcdb             0.0             9.0
13254056  66f57099e57842d2be2d2ec9ce69657f             0.0             2.0
13254057  0e2cbc5566c94beeb42e28fa7b7b8313             NaN             NaN
13254058  ba7b21dcd9004fad8881d772ea05bd14             0.0             0.0
13254059  4cee5a4de9224a13bc34af6cb4f88bfd             0.0             1.0

[13254060 rows x 3 columns]

In [10]:
loo

,creator,#comments_made,#comments_received,#posts
0,00012da44ef74e7ca5b77d17edbf8180,72.0,NaN,NaN
1,00012fc9ff674c2db03131a4df15d973,120.0,NaN,NaN
2,0001741c3596495c834983253dcb2254,27.0,NaN,NaN
3,0001ac250d644f828f5520839d371b8b,1.0,NaN,NaN
4,0002b9bcd61d4d73ba1f8a58d6cdb953,14.0,NaN,NaN
...,...,...,...,...
3146541,ffb018c89cee41bebb1066c90d05237f,NaN,NaN,1.0
3146542,ffb0ac6782b747f59d03555e64f04daa,NaN,NaN,1.0
3146543,ffb877b58c8d4bf9a246b521adda0505,NaN,NaN,1.0
3146544,ffeaa5c71fd64c5db52448d2bbf2fa54,NaN,NaN,1.0
3146545,fff4ecbcd2b54826af0c5921ecf09d94,NaN,NaN,1.0

In [11]:
goo=pd.merge(ta, loo, on='creator', how='inner')
goo

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,60.0,9.0,42.0
1,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,12.0,NaN,NaN
2,a078092e6e2df507bfd12db47108a7ef,9900.0,72.0,73.0,NaN,NaN
3,a078092e6e2df507bfd12db4712236a5,10000.0,27.0,NaN,1.0,1.0
4,a078092e6e2df507bfd12db47102e21b,3600.0,357.0,1.0,NaN,NaN
...,...,...,...,...,...,...
3146541,24d361d4bc8741318c5c880387b6cd6c,3.0,6.0,NaN,NaN,1.0
3146542,07aecb598eac4fe49b65c074802d3d19,1.0,10.0,NaN,NaN,1.0
3146543,2cb8443f3ee944d996b5f5b96b88800f,1.0,3.0,NaN,NaN,1.0
3146544,069e4f3b777f4d0da6f61af33c979a00,0.0,2.0,NaN,NaN,1.0
3146545,be5e4c2b5e5d4b02be663c2f1b5778af,4.0,6.0,NaN,NaN,2.0

- we only want profile characteristics of people who posted in the same time frame.

In [12]:
goo.to_csv("../largedata/new_range/same_range/parler_no_ratio.csv",index=False)

## Roles

In [13]:
goo

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,60.0,9.0,42.0
1,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,12.0,NaN,NaN
2,a078092e6e2df507bfd12db47108a7ef,9900.0,72.0,73.0,NaN,NaN
3,a078092e6e2df507bfd12db4712236a5,10000.0,27.0,NaN,1.0,1.0
4,a078092e6e2df507bfd12db47102e21b,3600.0,357.0,1.0,NaN,NaN
...,...,...,...,...,...,...
3146541,24d361d4bc8741318c5c880387b6cd6c,3.0,6.0,NaN,NaN,1.0
3146542,07aecb598eac4fe49b65c074802d3d19,1.0,10.0,NaN,NaN,1.0
3146543,2cb8443f3ee944d996b5f5b96b88800f,1.0,3.0,NaN,NaN,1.0
3146544,069e4f3b777f4d0da6f61af33c979a00,0.0,2.0,NaN,NaN,1.0
3146545,be5e4c2b5e5d4b02be663c2f1b5778af,4.0,6.0,NaN,NaN,2.0

In [14]:
udf=goo

In [15]:
udf

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,60.0,9.0,42.0
1,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,12.0,NaN,NaN
2,a078092e6e2df507bfd12db47108a7ef,9900.0,72.0,73.0,NaN,NaN
3,a078092e6e2df507bfd12db4712236a5,10000.0,27.0,NaN,1.0,1.0
4,a078092e6e2df507bfd12db47102e21b,3600.0,357.0,1.0,NaN,NaN
...,...,...,...,...,...,...
3146541,24d361d4bc8741318c5c880387b6cd6c,3.0,6.0,NaN,NaN,1.0
3146542,07aecb598eac4fe49b65c074802d3d19,1.0,10.0,NaN,NaN,1.0
3146543,2cb8443f3ee944d996b5f5b96b88800f,1.0,3.0,NaN,NaN,1.0
3146544,069e4f3b777f4d0da6f61af33c979a00,0.0,2.0,NaN,NaN,1.0
3146545,be5e4c2b5e5d4b02be663c2f1b5778af,4.0,6.0,NaN,NaN,2.0

In [16]:
udf[(udf["user_followers"].isna()&udf["user_following"].isna())]

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
3033855,b3589746e3db4e28ac13ba6073909263,NaN,NaN,NaN,1.0,1.0

In [17]:
udf = udf.dropna(subset=['user_followers', 'user_following'], how='all')

In [18]:
udf[udf["user_followers"].isna()]

Empty DataFrame
Columns: [creator, user_followers, user_following, #comments_made, #comments_received, #posts]
Index: []

In [19]:
udf[udf["user_following"].isna()]

Empty DataFrame
Columns: [creator, user_followers, user_following, #comments_made, #comments_received, #posts]
Index: []

In [20]:
udf[(udf["user_followers"]==0.0)&(udf["user_following"]==0.0)]

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
6306,08c1722063ad3d9601a601530d4607d0,0.0,0.0,1.0,NaN,NaN
10979,316647af393ef42edec353a1c35c75c9,0.0,0.0,1.0,NaN,NaN
13307,657ff86bd8ba4deabcb54511e32a1070,0.0,0.0,NaN,NaN,5.0
14300,112f5e019cbc46c6897a8ae4c0ba0f71,0.0,0.0,1.0,NaN,NaN
15342,23a08123cf7846468ceae5512944d911,0.0,0.0,NaN,NaN,1.0
...,...,...,...,...,...,...
3146509,609014e5b9864aa1b6b68e431296e3ee,0.0,0.0,NaN,NaN,1.0
3146521,18ff076b3a7646bab8153ab9a895a1d4,0.0,0.0,NaN,NaN,1.0
3146523,47be10be4c814376ba22008b9ae10d5f,0.0,0.0,NaN,NaN,1.0
3146528,a039167f63a0454ea455fec1fe263e96,0.0,0.0,NaN,NaN,1.0
3146539,f97e07665ed040f6aa6f75eb1e3cf83c,0.0,0.0,NaN,NaN,1.0

In [21]:
udf[udf["#posts"].isna()]

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
1,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,12.0,NaN,NaN
2,a078092e6e2df507bfd12db47108a7ef,9900.0,72.0,73.0,NaN,NaN
4,a078092e6e2df507bfd12db47102e21b,3600.0,357.0,1.0,NaN,NaN
5,a078092e6e2df507bfd12db47105ee05,3500.0,41.0,8.0,NaN,NaN
6,a078092e6e2df507bfd12db471270002,11000.0,324.0,1506.0,NaN,NaN
...,...,...,...,...,...,...
3146461,7ef340a653914af7ba74f43b10fc6603,0.0,3.0,1.0,NaN,NaN
3146466,eb3ef3ad3b5849978d643acb5f10aff5,0.0,0.0,1.0,NaN,NaN
3146470,1bea18aaf6934b9aa047c0146bfc3b32,2.0,16.0,1.0,NaN,NaN
3146473,4cd9ca3cc49247c09956fca5c7e2c3e7,0.0,7.0,1.0,NaN,NaN
3146483,f7f531f444464dba9818480a69d61604,1.0,6.0,2.0,NaN,NaN

In [22]:
udf[(udf["#posts"].isna()) & (~udf["#comments_received"].isna())]

,creator,user_followers,user_following,#comments_made,#comments_received,#posts
1519,e9a9d181bbee0a000445e420533fed99,85.0,100.0,11.0,12.0,NaN
1659,7a8576cf3ba014eb50d1c3b6322fe274,238.0,359.0,72.0,4.0,NaN
1699,54c32e82087f1b7130c653da0050e761,12.0,19.0,3.0,4.0,NaN
2261,5841b98300c21f04537a44380dc918d4,7500.0,9800.0,102.0,22.0,NaN
2441,b55883375e3bb951212f608e11ddea7e,155.0,105.0,NaN,1.0,NaN
...,...,...,...,...,...,...
886230,af63453df39c4060b9f39be0c997b0fd,2.0,8.0,NaN,1.0,NaN
886231,35bfffd52b1942b7837f20a24d6e53cd,5.0,7.0,1.0,4.0,NaN
886235,af5240519b034beeb83ce81a7f8d1555,4.0,8.0,1.0,2.0,NaN
886242,4e93235d7fa74531a317bef3eafe4254,6.0,4.0,NaN,1.0,NaN
886244,1c1e6529de8a4063bf971c971c2d0060,1.0,1.0,NaN,1.0,NaN