- This file has analysis with the range equivalent to Twitter

# Dotwin

In [11]:
import pandas as pd
import pyarrow
import matplotlib.pyplot as plt
import numpy as np

In [12]:
file_path_posts="../largedata/dotwin/dotwin_posts.pkl"
df1=pd.read_pickle(file_path_posts)
df1['timestamp'] = pd.to_datetime(df1['timestamp'])
# df1= df1[(df1['timestamp'] >= '2020-08-01')&(df1['timestamp'] <= '2020-12-04')]
df1= df1[(df1['timestamp'] >= '2020-08-01')]
df1

,site,pid,data_id,timestamp,votes,upvotes,downvotes,author,title,title_link,content,image
542,weekendgunnit,GbtUTN26,541386.0,2020-08-01 14:02:07,93.0,93.0,0.0,Rawnold_Reagan,The metric system,https://media.weekendgunnit.win/post/EhoeTTQ5.png,NaN,https://media.weekendgunnit.win/preview/GbtUTN...
543,weekendgunnit,GbtUTurZ,541541.0,2020-08-01 14:48:34,53.0,53.0,0.0,GarudaDarkblack,First AR build. How'd I do?,https://media.weekendgunnit.win/post/RmnLyD04....,NaN,https://media.weekendgunnit.win/preview/GbtUTu...
544,weekendgunnit,GbtUUT1n,541753.0,2020-08-01 15:43:10,57.0,57.0,0.0,Sunsetmal,"Gunsmiths were all booked. So I said fuck it, ...",https://media.weekendgunnit.win/post/H2TN9ToG....,NaN,https://media.weekendgunnit.win/preview/GbtUUT...
545,weekendgunnit,GbtVd8nT,542883.0,2020-08-01 20:09:04,77.0,77.0,0.0,arma,TFW you need to visit the wife's son but he go...,https://files.catbox.moe/ui7msf.png,NaN,https://media.weekendgunnit.win/preview/GbtVd8...
546,weekendgunnit,GbtWlnxx,543921.0,2020-08-02 01:07:04,40.0,46.0,6.0,Gewehr,Peace was never an option,https://media.weekendgunnit.win/post/HWSrddty....,NaN,https://media.weekendgunnit.win/preview/GbtWln...
...,...,...,...,...,...,...,...,...,...,...,...,...
227173,thedonald,12hRCKGD22,2028242.0,2021-02-09 15:00:28,3.0,3.0,0.0,KuzoKevin,"We, for supporting Trump, are extremists accor...",https://media.patriots.win/post/BN0bIlF2.png,NaN,https://media.patriots.win/preview/12hRCKGD22.png
227174,greatawakening,12hRCKGD23,2028243.0,2021-02-09 15:00:30,2.0,2.0,0.0,undine53,Biden Quietly Revokes Trump’s Ban on Chinese C...,https://thenationalpulse.com/breaking/biden-re...,NaN,NaN
227175,thedonald,12hRCKGD24,2028244.0,2021-02-09 15:00:50,2.0,2.0,0.0,Danleif,Night is day. Time to wake up!,https://media.patriots.win/post/mGyg7dra.jpeg,NaN,https://media.patriots.win/preview/12hRCKGD24.png
227176,thedonald,12hRCKGD25,2028245.0,2021-02-09 15:01:06,1.0,1.0,0.0,Awshit1,Big brother is always there to protek,https://media.patriots.win/post/CXV1vzrx.jpeg,NaN,https://media.patriots.win/preview/12hRCKGD25.png
227177,greatawakening,12hRCKGD26,2028246.0,2021-02-09 15:02:27,1.0,1.0,0.0,MikeWho,The people complaining about too many George p...,/p/12hRCKGD26/the-people-complaining-about-too/,Lol,NaN

In [13]:
df1=df1[["title"]]
df1

                                                    title
542                                     The metric system
543                           First AR build. How'd I do?
544     Gunsmiths were all booked. So I said fuck it, ...
545     TFW you need to visit the wife's son but he go...
546                             Peace was never an option
...                                                   ...
227173  We, for supporting Trump, are extremists accor...
227174  Biden Quietly Revokes Trump’s Ban on Chinese C...
227175                     Night is day. Time to wake up!
227176              Big brother is always there to protek
227177  The people complaining about too many George p...

[226636 rows x 1 columns]

In [16]:
df1

                                                    title
542                                     The metric system
543                           First AR build. How'd I do?
544     Gunsmiths were all booked. So I said fuck it, ...
545     TFW you need to visit the wife's son but he go...
546                             Peace was never an option
...                                                   ...
227173  We, for supporting Trump, are extremists accor...
227174  Biden Quietly Revokes Trump’s Ban on Chinese C...
227175                     Night is day. Time to wake up!
227176              Big brother is always there to protek
227177  The people complaining about too many George p...

[226636 rows x 1 columns]

In [18]:
df1.to_csv("../largedata/new_range/data_bert/dotwin.csv",index=False)